// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mqttconnector.implementation.SubscribeAction;

public class Subscribe extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use ConnectionDetail.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ConnectionDetail;
	private final mqttconnector.proxies.ConnectionDetail ConnectionDetail;
	private final java.lang.String Topic;
	private final java.lang.String OnMessageMicroflow;
	private final mqttconnector.proxies.QoS QoS;

	public Subscribe(
		IContext context,
		IMendixObject _connectionDetail,
		java.lang.String _topic,
		java.lang.String _onMessageMicroflow,
		java.lang.String _qoS
	)
	{
		super(context);
		this.__ConnectionDetail = _connectionDetail;
		this.ConnectionDetail = _connectionDetail == null ? null : mqttconnector.proxies.ConnectionDetail.initialize(getContext(), _connectionDetail);
		this.Topic = _topic;
		this.OnMessageMicroflow = _onMessageMicroflow;
		this.QoS = _qoS == null ? null : mqttconnector.proxies.QoS.valueOf(_qoS);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageReceivedListener messageReceivedListener = new MessageReceivedListener(getContext(), OnMessageMicroflow);
		String clientIdPrefix = String.valueOf(Core.getConfiguration().getConstantValue("MqttConnector.ClientIdPrefix")) + Core.getConfiguration().getXASId();
		SubscribeAction action = new SubscribeAction(clientIdPrefix, ConnectionDetail, Topic, messageReceivedListener,QoS);
		return action.execute();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Subscribe";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
