// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_New_VehicleBuilder(
		myfirstmodule.proxies.Ad _ad,
		myfirstmodule.proxies.Car _car
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_New_Vehicle");
		builder = builder.withParam("Ad", _ad);
		builder = builder.withParam("Car", _car);
		return builder;
	}

	public static void aCT_New_Vehicle(
		IContext context,
		myfirstmodule.proxies.Ad _ad,
		myfirstmodule.proxies.Car _car
	)
	{
		aCT_New_VehicleBuilder(
				_ad,
				_car
			)
			.execute(context);
	}
}
