// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Vehicle implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vehicleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Vehicle";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Brand("Brand"),
		Model("Model"),
		YearOfManufaturing("YearOfManufaturing"),
		Gearbox("Gearbox"),
		Color("Color");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Vehicle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Vehicle(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vehicleMendixObject)
	{
		if (vehicleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, vehicleMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.vehicleMendixObject = vehicleMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Vehicle initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MyFirstModule.Car", mendixObject.getType())) {
			return myfirstmodule.proxies.Car.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MyFirstModule.Motorcycle", mendixObject.getType())) {
			return myfirstmodule.proxies.Motorcycle.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MyFirstModule.Trucks", mendixObject.getType())) {
			return myfirstmodule.proxies.Trucks.initialize(context, mendixObject);
		}
		return new myfirstmodule.proxies.Vehicle(context, mendixObject);
	}

	public static myfirstmodule.proxies.Vehicle load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Vehicle.initialize(context, mendixObject);
	}

	public static java.util.List<? extends myfirstmodule.proxies.Vehicle> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Vehicle.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Brand
	 */
	public final java.lang.String getBrand()
	{
		return getBrand(getContext());
	}

	/**
	 * @param context
	 * @return value of Brand
	 */
	public final java.lang.String getBrand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Brand.toString());
	}

	/**
	 * Set value of Brand
	 * @param brand
	 */
	public final void setBrand(java.lang.String brand)
	{
		setBrand(getContext(), brand);
	}

	/**
	 * Set value of Brand
	 * @param context
	 * @param brand
	 */
	public final void setBrand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brand)
	{
		getMendixObject().setValue(context, MemberNames.Brand.toString(), brand);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * @return value of YearOfManufaturing
	 */
	public final java.lang.String getYearOfManufaturing()
	{
		return getYearOfManufaturing(getContext());
	}

	/**
	 * @param context
	 * @return value of YearOfManufaturing
	 */
	public final java.lang.String getYearOfManufaturing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YearOfManufaturing.toString());
	}

	/**
	 * Set value of YearOfManufaturing
	 * @param yearofmanufaturing
	 */
	public final void setYearOfManufaturing(java.lang.String yearofmanufaturing)
	{
		setYearOfManufaturing(getContext(), yearofmanufaturing);
	}

	/**
	 * Set value of YearOfManufaturing
	 * @param context
	 * @param yearofmanufaturing
	 */
	public final void setYearOfManufaturing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String yearofmanufaturing)
	{
		getMendixObject().setValue(context, MemberNames.YearOfManufaturing.toString(), yearofmanufaturing);
	}

	/**
	 * Get value of Gearbox
	 * @param gearbox
	 */
	public final myfirstmodule.proxies.ENUM_Car_Gearbox getGearbox()
	{
		return getGearbox(getContext());
	}

	/**
	 * @param context
	 * @return value of Gearbox
	 */
	public final myfirstmodule.proxies.ENUM_Car_Gearbox getGearbox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gearbox.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Car_Gearbox.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gearbox
	 * @param gearbox
	 */
	public final void setGearbox(myfirstmodule.proxies.ENUM_Car_Gearbox gearbox)
	{
		setGearbox(getContext(), gearbox);
	}

	/**
	 * Set value of Gearbox
	 * @param context
	 * @param gearbox
	 */
	public final void setGearbox(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Car_Gearbox gearbox)
	{
		if (gearbox != null) {
			getMendixObject().setValue(context, MemberNames.Gearbox.toString(), gearbox.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Gearbox.toString(), null);
		}
	}

	/**
	 * Get value of Color
	 * @param color
	 */
	public final myfirstmodule.proxies.ENUM_Car_Colors getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final myfirstmodule.proxies.ENUM_Car_Colors getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Color.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Car_Colors.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(myfirstmodule.proxies.ENUM_Car_Colors color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Car_Colors color)
	{
		if (color != null) {
			getMendixObject().setValue(context, MemberNames.Color.toString(), color.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Color.toString(), null);
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vehicleMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Vehicle that = (myfirstmodule.proxies.Vehicle) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
