// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttconnector.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the MqttConnector module

	public static java.lang.String getClientIdPrefix()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MqttConnector.ClientIdPrefix");
	}

	/**
	* This key will be used to encrypt and decrypt email account passwords.
	* The length of this key must be 32 characters.
	*/
	public static java.lang.String getEncryptionKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MqttConnector.EncryptionKey");
	}
}