// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restconsume.proxies;

public class Summary implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RESTConsume.Summary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_type("_type"),
		Title("Title"),
		Displaytitle("Displaytitle"),
		Wikibase_item("Wikibase_item"),
		Pageid("Pageid"),
		Lang("Lang"),
		Dir("Dir"),
		Revision("Revision"),
		Tid("Tid"),
		Timestamp("Timestamp"),
		Description("Description"),
		Description_source("Description_source"),
		Extract("Extract"),
		Extract_html("Extract_html"),
		Namespace_Summary("RESTConsume.Namespace_Summary"),
		Titles_Summary("RESTConsume.Titles_Summary"),
		Thumbnail_Summary("RESTConsume.Thumbnail_Summary"),
		Originalimage_Summary("RESTConsume.Originalimage_Summary"),
		Content_urls_Summary("RESTConsume.Content_urls_Summary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Summary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Summary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject)
	{
		if (summaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, summaryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.summaryMendixObject = summaryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static restconsume.proxies.Summary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new restconsume.proxies.Summary(context, mendixObject);
	}

	public static restconsume.proxies.Summary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return restconsume.proxies.Summary.initialize(context, mendixObject);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Displaytitle
	 */
	public final java.lang.String getDisplaytitle()
	{
		return getDisplaytitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Displaytitle
	 */
	public final java.lang.String getDisplaytitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Displaytitle.toString());
	}

	/**
	 * Set value of Displaytitle
	 * @param displaytitle
	 */
	public final void setDisplaytitle(java.lang.String displaytitle)
	{
		setDisplaytitle(getContext(), displaytitle);
	}

	/**
	 * Set value of Displaytitle
	 * @param context
	 * @param displaytitle
	 */
	public final void setDisplaytitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displaytitle)
	{
		getMendixObject().setValue(context, MemberNames.Displaytitle.toString(), displaytitle);
	}

	/**
	 * @return value of Wikibase_item
	 */
	public final java.lang.String getWikibase_item()
	{
		return getWikibase_item(getContext());
	}

	/**
	 * @param context
	 * @return value of Wikibase_item
	 */
	public final java.lang.String getWikibase_item(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wikibase_item.toString());
	}

	/**
	 * Set value of Wikibase_item
	 * @param wikibase_item
	 */
	public final void setWikibase_item(java.lang.String wikibase_item)
	{
		setWikibase_item(getContext(), wikibase_item);
	}

	/**
	 * Set value of Wikibase_item
	 * @param context
	 * @param wikibase_item
	 */
	public final void setWikibase_item(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wikibase_item)
	{
		getMendixObject().setValue(context, MemberNames.Wikibase_item.toString(), wikibase_item);
	}

	/**
	 * @return value of Pageid
	 */
	public final java.lang.Integer getPageid()
	{
		return getPageid(getContext());
	}

	/**
	 * @param context
	 * @return value of Pageid
	 */
	public final java.lang.Integer getPageid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pageid.toString());
	}

	/**
	 * Set value of Pageid
	 * @param pageid
	 */
	public final void setPageid(java.lang.Integer pageid)
	{
		setPageid(getContext(), pageid);
	}

	/**
	 * Set value of Pageid
	 * @param context
	 * @param pageid
	 */
	public final void setPageid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pageid)
	{
		getMendixObject().setValue(context, MemberNames.Pageid.toString(), pageid);
	}

	/**
	 * @return value of Lang
	 */
	public final java.lang.String getLang()
	{
		return getLang(getContext());
	}

	/**
	 * @param context
	 * @return value of Lang
	 */
	public final java.lang.String getLang(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Lang.toString());
	}

	/**
	 * Set value of Lang
	 * @param lang
	 */
	public final void setLang(java.lang.String lang)
	{
		setLang(getContext(), lang);
	}

	/**
	 * Set value of Lang
	 * @param context
	 * @param lang
	 */
	public final void setLang(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lang)
	{
		getMendixObject().setValue(context, MemberNames.Lang.toString(), lang);
	}

	/**
	 * @return value of Dir
	 */
	public final java.lang.String getDir()
	{
		return getDir(getContext());
	}

	/**
	 * @param context
	 * @return value of Dir
	 */
	public final java.lang.String getDir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dir.toString());
	}

	/**
	 * Set value of Dir
	 * @param dir
	 */
	public final void setDir(java.lang.String dir)
	{
		setDir(getContext(), dir);
	}

	/**
	 * Set value of Dir
	 * @param context
	 * @param dir
	 */
	public final void setDir(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dir)
	{
		getMendixObject().setValue(context, MemberNames.Dir.toString(), dir);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of Tid
	 */
	public final java.lang.String getTid()
	{
		return getTid(getContext());
	}

	/**
	 * @param context
	 * @return value of Tid
	 */
	public final java.lang.String getTid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tid.toString());
	}

	/**
	 * Set value of Tid
	 * @param tid
	 */
	public final void setTid(java.lang.String tid)
	{
		setTid(getContext(), tid);
	}

	/**
	 * Set value of Tid
	 * @param context
	 * @param tid
	 */
	public final void setTid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tid)
	{
		getMendixObject().setValue(context, MemberNames.Tid.toString(), tid);
	}

	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Description_source
	 */
	public final java.lang.String getDescription_source()
	{
		return getDescription_source(getContext());
	}

	/**
	 * @param context
	 * @return value of Description_source
	 */
	public final java.lang.String getDescription_source(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description_source.toString());
	}

	/**
	 * Set value of Description_source
	 * @param description_source
	 */
	public final void setDescription_source(java.lang.String description_source)
	{
		setDescription_source(getContext(), description_source);
	}

	/**
	 * Set value of Description_source
	 * @param context
	 * @param description_source
	 */
	public final void setDescription_source(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description_source)
	{
		getMendixObject().setValue(context, MemberNames.Description_source.toString(), description_source);
	}

	/**
	 * @return value of Extract
	 */
	public final java.lang.String getExtract()
	{
		return getExtract(getContext());
	}

	/**
	 * @param context
	 * @return value of Extract
	 */
	public final java.lang.String getExtract(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Extract.toString());
	}

	/**
	 * Set value of Extract
	 * @param extract
	 */
	public final void setExtract(java.lang.String extract)
	{
		setExtract(getContext(), extract);
	}

	/**
	 * Set value of Extract
	 * @param context
	 * @param extract
	 */
	public final void setExtract(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extract)
	{
		getMendixObject().setValue(context, MemberNames.Extract.toString(), extract);
	}

	/**
	 * @return value of Extract_html
	 */
	public final java.lang.String getExtract_html()
	{
		return getExtract_html(getContext());
	}

	/**
	 * @param context
	 * @return value of Extract_html
	 */
	public final java.lang.String getExtract_html(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Extract_html.toString());
	}

	/**
	 * Set value of Extract_html
	 * @param extract_html
	 */
	public final void setExtract_html(java.lang.String extract_html)
	{
		setExtract_html(getContext(), extract_html);
	}

	/**
	 * Set value of Extract_html
	 * @param context
	 * @param extract_html
	 */
	public final void setExtract_html(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extract_html)
	{
		getMendixObject().setValue(context, MemberNames.Extract_html.toString(), extract_html);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Namespace_Summary
	 */
	public final restconsume.proxies.Namespace getNamespace_Summary() throws com.mendix.core.CoreException
	{
		return getNamespace_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Namespace_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Namespace getNamespace_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Namespace result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Namespace_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Namespace.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Namespace_Summary
	 * @param namespace_summary
	 */
	public final void setNamespace_Summary(restconsume.proxies.Namespace namespace_summary)
	{
		setNamespace_Summary(getContext(), namespace_summary);
	}

	/**
	 * Set value of Namespace_Summary
	 * @param context
	 * @param namespace_summary
	 */
	public final void setNamespace_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Namespace namespace_summary)
	{
		if (namespace_summary == null) {
			getMendixObject().setValue(context, MemberNames.Namespace_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Namespace_Summary.toString(), namespace_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Titles_Summary
	 */
	public final restconsume.proxies.Titles getTitles_Summary() throws com.mendix.core.CoreException
	{
		return getTitles_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Titles_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Titles getTitles_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Titles result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Titles_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Titles.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Titles_Summary
	 * @param titles_summary
	 */
	public final void setTitles_Summary(restconsume.proxies.Titles titles_summary)
	{
		setTitles_Summary(getContext(), titles_summary);
	}

	/**
	 * Set value of Titles_Summary
	 * @param context
	 * @param titles_summary
	 */
	public final void setTitles_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Titles titles_summary)
	{
		if (titles_summary == null) {
			getMendixObject().setValue(context, MemberNames.Titles_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Titles_Summary.toString(), titles_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Thumbnail_Summary
	 */
	public final restconsume.proxies.Thumbnail getThumbnail_Summary() throws com.mendix.core.CoreException
	{
		return getThumbnail_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Thumbnail_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Thumbnail getThumbnail_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Thumbnail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Thumbnail_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Thumbnail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Thumbnail_Summary
	 * @param thumbnail_summary
	 */
	public final void setThumbnail_Summary(restconsume.proxies.Thumbnail thumbnail_summary)
	{
		setThumbnail_Summary(getContext(), thumbnail_summary);
	}

	/**
	 * Set value of Thumbnail_Summary
	 * @param context
	 * @param thumbnail_summary
	 */
	public final void setThumbnail_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Thumbnail thumbnail_summary)
	{
		if (thumbnail_summary == null) {
			getMendixObject().setValue(context, MemberNames.Thumbnail_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Thumbnail_Summary.toString(), thumbnail_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Originalimage_Summary
	 */
	public final restconsume.proxies.Originalimage getOriginalimage_Summary() throws com.mendix.core.CoreException
	{
		return getOriginalimage_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Originalimage_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Originalimage getOriginalimage_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Originalimage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Originalimage_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Originalimage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Originalimage_Summary
	 * @param originalimage_summary
	 */
	public final void setOriginalimage_Summary(restconsume.proxies.Originalimage originalimage_summary)
	{
		setOriginalimage_Summary(getContext(), originalimage_summary);
	}

	/**
	 * Set value of Originalimage_Summary
	 * @param context
	 * @param originalimage_summary
	 */
	public final void setOriginalimage_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Originalimage originalimage_summary)
	{
		if (originalimage_summary == null) {
			getMendixObject().setValue(context, MemberNames.Originalimage_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Originalimage_Summary.toString(), originalimage_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Content_urls_Summary
	 */
	public final restconsume.proxies.Content_urls getContent_urls_Summary() throws com.mendix.core.CoreException
	{
		return getContent_urls_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Content_urls_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Content_urls getContent_urls_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Content_urls result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Content_urls_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Content_urls.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Content_urls_Summary
	 * @param content_urls_summary
	 */
	public final void setContent_urls_Summary(restconsume.proxies.Content_urls content_urls_summary)
	{
		setContent_urls_Summary(getContext(), content_urls_summary);
	}

	/**
	 * Set value of Content_urls_Summary
	 * @param context
	 * @param content_urls_summary
	 */
	public final void setContent_urls_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Content_urls content_urls_summary)
	{
		if (content_urls_summary == null) {
			getMendixObject().setValue(context, MemberNames.Content_urls_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Content_urls_Summary.toString(), content_urls_summary.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return summaryMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final restconsume.proxies.Summary that = (restconsume.proxies.Summary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
