// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restconsume.proxies;

public class Titles implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titlesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RESTConsume.Titles";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Canonical("Canonical"),
		Normalized("Normalized"),
		Display("Display"),
		Titles_Summary("RESTConsume.Titles_Summary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Titles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Titles(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titlesMendixObject)
	{
		if (titlesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, titlesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titlesMendixObject = titlesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static restconsume.proxies.Titles initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new restconsume.proxies.Titles(context, mendixObject);
	}

	public static restconsume.proxies.Titles load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return restconsume.proxies.Titles.initialize(context, mendixObject);
	}

	/**
	 * @return value of Canonical
	 */
	public final java.lang.String getCanonical()
	{
		return getCanonical(getContext());
	}

	/**
	 * @param context
	 * @return value of Canonical
	 */
	public final java.lang.String getCanonical(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Canonical.toString());
	}

	/**
	 * Set value of Canonical
	 * @param canonical
	 */
	public final void setCanonical(java.lang.String canonical)
	{
		setCanonical(getContext(), canonical);
	}

	/**
	 * Set value of Canonical
	 * @param context
	 * @param canonical
	 */
	public final void setCanonical(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String canonical)
	{
		getMendixObject().setValue(context, MemberNames.Canonical.toString(), canonical);
	}

	/**
	 * @return value of Normalized
	 */
	public final java.lang.String getNormalized()
	{
		return getNormalized(getContext());
	}

	/**
	 * @param context
	 * @return value of Normalized
	 */
	public final java.lang.String getNormalized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Normalized.toString());
	}

	/**
	 * Set value of Normalized
	 * @param normalized
	 */
	public final void setNormalized(java.lang.String normalized)
	{
		setNormalized(getContext(), normalized);
	}

	/**
	 * Set value of Normalized
	 * @param context
	 * @param normalized
	 */
	public final void setNormalized(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String normalized)
	{
		getMendixObject().setValue(context, MemberNames.Normalized.toString(), normalized);
	}

	/**
	 * @return value of Display
	 */
	public final java.lang.String getDisplay()
	{
		return getDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of Display
	 */
	public final java.lang.String getDisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Display.toString());
	}

	/**
	 * Set value of Display
	 * @param display
	 */
	public final void setDisplay(java.lang.String display)
	{
		setDisplay(getContext(), display);
	}

	/**
	 * Set value of Display
	 * @param context
	 * @param display
	 */
	public final void setDisplay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String display)
	{
		getMendixObject().setValue(context, MemberNames.Display.toString(), display);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Titles_Summary
	 */
	public final restconsume.proxies.Summary getTitles_Summary() throws com.mendix.core.CoreException
	{
		return getTitles_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Titles_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final restconsume.proxies.Summary getTitles_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restconsume.proxies.Summary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Titles_Summary.toString());
		if (identifier != null) {
			result = restconsume.proxies.Summary.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Titles_Summary
	 * @param titles_summary
	 */
	public final void setTitles_Summary(restconsume.proxies.Summary titles_summary)
	{
		setTitles_Summary(getContext(), titles_summary);
	}

	/**
	 * Set value of Titles_Summary
	 * @param context
	 * @param titles_summary
	 */
	public final void setTitles_Summary(com.mendix.systemwideinterfaces.core.IContext context, restconsume.proxies.Summary titles_summary)
	{
		if (titles_summary == null) {
			getMendixObject().setValue(context, MemberNames.Titles_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Titles_Summary.toString(), titles_summary.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titlesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final restconsume.proxies.Titles that = (restconsume.proxies.Titles) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
