// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vacationmanagement.proxies;

public class VacationRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vacationRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VacationManagement.VacationRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		Status("Status"),
		VacationRequest_Submitter("VacationManagement.VacationRequest_Submitter"),
		VacationRequest_Approver("VacationManagement.VacationRequest_Approver");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VacationRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected VacationRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vacationRequestMendixObject)
	{
		if (vacationRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, vacationRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.vacationRequestMendixObject = vacationRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static vacationmanagement.proxies.VacationRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vacationmanagement.proxies.VacationRequest(context, mendixObject);
	}

	public static vacationmanagement.proxies.VacationRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vacationmanagement.proxies.VacationRequest.initialize(context, mendixObject);
	}

	public static java.util.List<vacationmanagement.proxies.VacationRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> vacationmanagement.proxies.VacationRequest.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final vacationmanagement.proxies.ENUM_VacationRequestStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final vacationmanagement.proxies.ENUM_VacationRequestStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return vacationmanagement.proxies.ENUM_VacationRequestStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(vacationmanagement.proxies.ENUM_VacationRequestStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, vacationmanagement.proxies.ENUM_VacationRequestStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VacationRequest_Submitter
	 */
	public final administration.proxies.Account getVacationRequest_Submitter() throws com.mendix.core.CoreException
	{
		return getVacationRequest_Submitter(getContext());
	}

	/**
	 * @param context
	 * @return value of VacationRequest_Submitter
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getVacationRequest_Submitter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VacationRequest_Submitter.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VacationRequest_Submitter
	 * @param vacationrequest_submitter
	 */
	public final void setVacationRequest_Submitter(administration.proxies.Account vacationrequest_submitter)
	{
		setVacationRequest_Submitter(getContext(), vacationrequest_submitter);
	}

	/**
	 * Set value of VacationRequest_Submitter
	 * @param context
	 * @param vacationrequest_submitter
	 */
	public final void setVacationRequest_Submitter(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account vacationrequest_submitter)
	{
		if (vacationrequest_submitter == null) {
			getMendixObject().setValue(context, MemberNames.VacationRequest_Submitter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VacationRequest_Submitter.toString(), vacationrequest_submitter.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VacationRequest_Approver
	 */
	public final administration.proxies.Account getVacationRequest_Approver() throws com.mendix.core.CoreException
	{
		return getVacationRequest_Approver(getContext());
	}

	/**
	 * @param context
	 * @return value of VacationRequest_Approver
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getVacationRequest_Approver(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VacationRequest_Approver.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VacationRequest_Approver
	 * @param vacationrequest_approver
	 */
	public final void setVacationRequest_Approver(administration.proxies.Account vacationrequest_approver)
	{
		setVacationRequest_Approver(getContext(), vacationrequest_approver);
	}

	/**
	 * Set value of VacationRequest_Approver
	 * @param context
	 * @param vacationrequest_approver
	 */
	public final void setVacationRequest_Approver(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account vacationrequest_approver)
	{
		if (vacationrequest_approver == null) {
			getMendixObject().setValue(context, MemberNames.VacationRequest_Approver.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VacationRequest_Approver.toString(), vacationrequest_approver.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vacationRequestMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vacationmanagement.proxies.VacationRequest that = (vacationmanagement.proxies.VacationRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
