// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notification.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Notification module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Booking_ComingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notification.ACT_Booking_Coming");
		return builder;
	}

	public static void aCT_Booking_Coming(IContext context)
	{
		aCT_Booking_ComingBuilder().execute(context);
	}
}
