// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Logo_Team extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Logo_Team";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Team_Logo_Team("MyFirstModule.Team_Logo_Team");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Logo_Team(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Logo_Team(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logo_TeamMendixObject)
	{
		super(context, logo_TeamMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, logo_TeamMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Logo_Team initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Logo_Team(context, mendixObject);
	}

	public static myfirstmodule.proxies.Logo_Team load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Logo_Team.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Logo_Team> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Logo_Team.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Team_Logo_Team
	 */
	public final myfirstmodule.proxies.Team getTeam_Logo_Team() throws com.mendix.core.CoreException
	{
		return getTeam_Logo_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_Logo_Team
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Team getTeam_Logo_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Team_Logo_Team.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Team_Logo_Team
	 * @param team_logo_team
	 */
	public final void setTeam_Logo_Team(myfirstmodule.proxies.Team team_logo_team)
	{
		setTeam_Logo_Team(getContext(), team_logo_team);
	}

	/**
	 * Set value of Team_Logo_Team
	 * @param context
	 * @param team_logo_team
	 */
	public final void setTeam_Logo_Team(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Team team_logo_team)
	{
		if (team_logo_team == null) {
			getMendixObject().setValue(context, MemberNames.Team_Logo_Team.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Team_Logo_Team.toString(), team_logo_team.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Logo_Team that = (myfirstmodule.proxies.Logo_Team) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
