// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Player implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject playerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Player";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Number("Number"),
		Player_Team("MyFirstModule.Player_Team"),
		Captain_Team("MyFirstModule.Captain_Team"),
		Player_Logo_Player("MyFirstModule.Player_Logo_Player");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Player(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Player(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject playerMendixObject)
	{
		if (playerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, playerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.playerMendixObject = playerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Player initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Player(context, mendixObject);
	}

	public static myfirstmodule.proxies.Player load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Player.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Player> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Player.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.String getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.String getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.String number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Player_Team
	 */
	public final myfirstmodule.proxies.Team getPlayer_Team() throws com.mendix.core.CoreException
	{
		return getPlayer_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of Player_Team
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Team getPlayer_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Player_Team.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Player_Team
	 * @param player_team
	 */
	public final void setPlayer_Team(myfirstmodule.proxies.Team player_team)
	{
		setPlayer_Team(getContext(), player_team);
	}

	/**
	 * Set value of Player_Team
	 * @param context
	 * @param player_team
	 */
	public final void setPlayer_Team(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Team player_team)
	{
		if (player_team == null) {
			getMendixObject().setValue(context, MemberNames.Player_Team.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Player_Team.toString(), player_team.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Captain_Team
	 */
	public final myfirstmodule.proxies.Team getCaptain_Team() throws com.mendix.core.CoreException
	{
		return getCaptain_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of Captain_Team
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Team getCaptain_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Captain_Team.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Captain_Team
	 * @param captain_team
	 */
	public final void setCaptain_Team(myfirstmodule.proxies.Team captain_team)
	{
		setCaptain_Team(getContext(), captain_team);
	}

	/**
	 * Set value of Captain_Team
	 * @param context
	 * @param captain_team
	 */
	public final void setCaptain_Team(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Team captain_team)
	{
		if (captain_team == null) {
			getMendixObject().setValue(context, MemberNames.Captain_Team.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Captain_Team.toString(), captain_team.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Player_Logo_Player
	 */
	public final myfirstmodule.proxies.Player_Logo getPlayer_Logo_Player() throws com.mendix.core.CoreException
	{
		return getPlayer_Logo_Player(getContext());
	}

	/**
	 * @param context
	 * @return value of Player_Logo_Player
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Player_Logo getPlayer_Logo_Player(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Player_Logo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Player_Logo_Player.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Player_Logo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Player_Logo_Player
	 * @param player_logo_player
	 */
	public final void setPlayer_Logo_Player(myfirstmodule.proxies.Player_Logo player_logo_player)
	{
		setPlayer_Logo_Player(getContext(), player_logo_player);
	}

	/**
	 * Set value of Player_Logo_Player
	 * @param context
	 * @param player_logo_player
	 */
	public final void setPlayer_Logo_Player(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Player_Logo player_logo_player)
	{
		if (player_logo_player == null) {
			getMendixObject().setValue(context, MemberNames.Player_Logo_Player.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Player_Logo_Player.toString(), player_logo_player.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return playerMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Player that = (myfirstmodule.proxies.Player) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
