// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Player_Logo extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Player_Logo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Player_Logo_Player("MyFirstModule.Player_Logo_Player");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Player_Logo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Player_Logo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject player_LogoMendixObject)
	{
		super(context, player_LogoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, player_LogoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Player_Logo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Player_Logo(context, mendixObject);
	}

	public static myfirstmodule.proxies.Player_Logo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Player_Logo.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Player_Logo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Player_Logo.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Player_Logo_Player
	 */
	public final myfirstmodule.proxies.Player getPlayer_Logo_Player() throws com.mendix.core.CoreException
	{
		return getPlayer_Logo_Player(getContext());
	}

	/**
	 * @param context
	 * @return value of Player_Logo_Player
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Player getPlayer_Logo_Player(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Player result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Player_Logo_Player.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Player.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Player_Logo_Player
	 * @param player_logo_player
	 */
	public final void setPlayer_Logo_Player(myfirstmodule.proxies.Player player_logo_player)
	{
		setPlayer_Logo_Player(getContext(), player_logo_player);
	}

	/**
	 * Set value of Player_Logo_Player
	 * @param context
	 * @param player_logo_player
	 */
	public final void setPlayer_Logo_Player(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Player player_logo_player)
	{
		if (player_logo_player == null) {
			getMendixObject().setValue(context, MemberNames.Player_Logo_Player.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Player_Logo_Player.toString(), player_logo_player.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Player_Logo that = (myfirstmodule.proxies.Player_Logo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
