// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rooms.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Rooms module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Room_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Rooms.ACT_Room_Create");
		return builder;
	}

	public static void aCT_Room_Create(IContext context)
	{
		aCT_Room_CreateBuilder().execute(context);
	}
}
