// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GalleryMotorcycle extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GalleryMotorcycle";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		GalleryMotorcycle_Motorcycle("MyFirstModule.GalleryMotorcycle_Motorcycle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GalleryMotorcycle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GalleryMotorcycle(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject galleryMotorcycleMendixObject)
	{
		super(context, galleryMotorcycleMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, galleryMotorcycleMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.GalleryMotorcycle initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GalleryMotorcycle(context, mendixObject);
	}

	public static myfirstmodule.proxies.GalleryMotorcycle load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GalleryMotorcycle.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.GalleryMotorcycle> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.GalleryMotorcycle.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GalleryMotorcycle_Motorcycle
	 */
	public final myfirstmodule.proxies.Motorcycle getGalleryMotorcycle_Motorcycle() throws com.mendix.core.CoreException
	{
		return getGalleryMotorcycle_Motorcycle(getContext());
	}

	/**
	 * @param context
	 * @return value of GalleryMotorcycle_Motorcycle
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Motorcycle getGalleryMotorcycle_Motorcycle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Motorcycle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GalleryMotorcycle_Motorcycle.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Motorcycle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GalleryMotorcycle_Motorcycle
	 * @param gallerymotorcycle_motorcycle
	 */
	public final void setGalleryMotorcycle_Motorcycle(myfirstmodule.proxies.Motorcycle gallerymotorcycle_motorcycle)
	{
		setGalleryMotorcycle_Motorcycle(getContext(), gallerymotorcycle_motorcycle);
	}

	/**
	 * Set value of GalleryMotorcycle_Motorcycle
	 * @param context
	 * @param gallerymotorcycle_motorcycle
	 */
	public final void setGalleryMotorcycle_Motorcycle(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Motorcycle gallerymotorcycle_motorcycle)
	{
		if (gallerymotorcycle_motorcycle == null) {
			getMendixObject().setValue(context, MemberNames.GalleryMotorcycle_Motorcycle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GalleryMotorcycle_Motorcycle.toString(), gallerymotorcycle_motorcycle.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GalleryMotorcycle that = (myfirstmodule.proxies.GalleryMotorcycle) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
