// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Gallery extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Gallery";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Gallery_Vehicle("MyFirstModule.Gallery_Vehicle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Gallery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Gallery(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject galleryMendixObject)
	{
		super(context, galleryMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, galleryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Gallery initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Gallery(context, mendixObject);
	}

	public static myfirstmodule.proxies.Gallery load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Gallery.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Gallery> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Gallery.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Gallery_Vehicle
	 */
	public final myfirstmodule.proxies.Vehicle getGallery_Vehicle() throws com.mendix.core.CoreException
	{
		return getGallery_Vehicle(getContext());
	}

	/**
	 * @param context
	 * @return value of Gallery_Vehicle
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Vehicle getGallery_Vehicle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Vehicle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Gallery_Vehicle.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Vehicle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Gallery_Vehicle
	 * @param gallery_vehicle
	 */
	public final void setGallery_Vehicle(myfirstmodule.proxies.Vehicle gallery_vehicle)
	{
		setGallery_Vehicle(getContext(), gallery_vehicle);
	}

	/**
	 * Set value of Gallery_Vehicle
	 * @param context
	 * @param gallery_vehicle
	 */
	public final void setGallery_Vehicle(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Vehicle gallery_vehicle)
	{
		if (gallery_vehicle == null) {
			getMendixObject().setValue(context, MemberNames.Gallery_Vehicle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Gallery_Vehicle.toString(), gallery_vehicle.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Gallery that = (myfirstmodule.proxies.Gallery) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
