// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forgotpassword.proxies;

public class EmailTemplateSMTP implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailTemplateSMTPMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ForgotPassword.EmailTemplateSMTP";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmailTemplateSMTP_EmailTemplate("ForgotPassword.EmailTemplateSMTP_EmailTemplate"),
		EmailTemplateSMTP_EmailAccount("ForgotPassword.EmailTemplateSMTP_EmailAccount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailTemplateSMTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailTemplateSMTP(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailTemplateSMTPMendixObject)
	{
		if (emailTemplateSMTPMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailTemplateSMTPMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailTemplateSMTPMendixObject = emailTemplateSMTPMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static forgotpassword.proxies.EmailTemplateSMTP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forgotpassword.proxies.EmailTemplateSMTP(context, mendixObject);
	}

	public static forgotpassword.proxies.EmailTemplateSMTP load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forgotpassword.proxies.EmailTemplateSMTP.initialize(context, mendixObject);
	}

	public static java.util.List<forgotpassword.proxies.EmailTemplateSMTP> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> forgotpassword.proxies.EmailTemplateSMTP.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailTemplateSMTP_EmailTemplate
	 */
	public final email_connector.proxies.EmailTemplate getEmailTemplateSMTP_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getEmailTemplateSMTP_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailTemplateSMTP_EmailTemplate
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailTemplate getEmailTemplateSMTP_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailTemplateSMTP_EmailTemplate.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailTemplate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailTemplateSMTP_EmailTemplate
	 * @param emailtemplatesmtp_emailtemplate
	 */
	public final void setEmailTemplateSMTP_EmailTemplate(email_connector.proxies.EmailTemplate emailtemplatesmtp_emailtemplate)
	{
		setEmailTemplateSMTP_EmailTemplate(getContext(), emailtemplatesmtp_emailtemplate);
	}

	/**
	 * Set value of EmailTemplateSMTP_EmailTemplate
	 * @param context
	 * @param emailtemplatesmtp_emailtemplate
	 */
	public final void setEmailTemplateSMTP_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailTemplate emailtemplatesmtp_emailtemplate)
	{
		if (emailtemplatesmtp_emailtemplate == null) {
			getMendixObject().setValue(context, MemberNames.EmailTemplateSMTP_EmailTemplate.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailTemplateSMTP_EmailTemplate.toString(), emailtemplatesmtp_emailtemplate.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailTemplateSMTP_EmailAccount
	 */
	public final email_connector.proxies.EmailAccount getEmailTemplateSMTP_EmailAccount() throws com.mendix.core.CoreException
	{
		return getEmailTemplateSMTP_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailTemplateSMTP_EmailAccount
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailAccount getEmailTemplateSMTP_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailTemplateSMTP_EmailAccount.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailAccount.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailTemplateSMTP_EmailAccount
	 * @param emailtemplatesmtp_emailaccount
	 */
	public final void setEmailTemplateSMTP_EmailAccount(email_connector.proxies.EmailAccount emailtemplatesmtp_emailaccount)
	{
		setEmailTemplateSMTP_EmailAccount(getContext(), emailtemplatesmtp_emailaccount);
	}

	/**
	 * Set value of EmailTemplateSMTP_EmailAccount
	 * @param context
	 * @param emailtemplatesmtp_emailaccount
	 */
	public final void setEmailTemplateSMTP_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailAccount emailtemplatesmtp_emailaccount)
	{
		if (emailtemplatesmtp_emailaccount == null) {
			getMendixObject().setValue(context, MemberNames.EmailTemplateSMTP_EmailAccount.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailTemplateSMTP_EmailAccount.toString(), emailtemplatesmtp_emailaccount.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailTemplateSMTPMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forgotpassword.proxies.EmailTemplateSMTP that = (forgotpassword.proxies.EmailTemplateSMTP) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
