// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the UserManagement module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Registration_CreateTeamMemberBuilder(
		usermanagement.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserManagement.ACT_Registration_CreateTeamMember");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Registration_CreateTeamMember(
		IContext context,
		usermanagement.proxies.Registration _registration
	)
	{
		aCT_Registration_CreateTeamMemberBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_EditBuilder(
		usermanagement.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserManagement.ACT_User_Edit");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_User_Edit(
		IContext context,
		usermanagement.proxies.User _user
	)
	{
		aCT_User_EditBuilder(
				_user
			)
			.execute(context);
	}
}
