// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttconnector.proxies;

public class ConnectionDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject connectionDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MqttConnector.ConnectionDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		BrokerHost("BrokerHost"),
		BrokerPort("BrokerPort"),
		TimeOut("TimeOut"),
		SSL("SSL"),
		KeepAliveTime("KeepAliveTime"),
		CleanSession("CleanSession"),
		AutoReconnect("AutoReconnect"),
		CA("CA"),
		ClientKey("ClientKey"),
		ClientCertificate("ClientCertificate"),
		CertificatePassword("CertificatePassword"),
		UserName("UserName"),
		Password("Password"),
		AuthenticationMethod("AuthenticationMethod"),
		AdvancedSettingsToggle("AdvancedSettingsToggle"),
		HostnameVerification("HostnameVerification"),
		MaxInFlight("MaxInFlight"),
		MaxReconnectDelay("MaxReconnectDelay"),
		SetWill("SetWill"),
		WillTopic("WillTopic"),
		WillPayLoad("WillPayLoad"),
		WillQoS("WillQoS"),
		WillRetain("WillRetain"),
		OperationTimeout("OperationTimeout");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConnectionDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConnectionDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject connectionDetailMendixObject)
	{
		if (connectionDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, connectionDetailMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.connectionDetailMendixObject = connectionDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mqttconnector.proxies.ConnectionDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mqttconnector.proxies.ConnectionDetail(context, mendixObject);
	}

	public static mqttconnector.proxies.ConnectionDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mqttconnector.proxies.ConnectionDetail.initialize(context, mendixObject);
	}

	public static java.util.List<mqttconnector.proxies.ConnectionDetail> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mqttconnector.proxies.ConnectionDetail.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of BrokerHost
	 */
	public final java.lang.String getBrokerHost()
	{
		return getBrokerHost(getContext());
	}

	/**
	 * @param context
	 * @return value of BrokerHost
	 */
	public final java.lang.String getBrokerHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrokerHost.toString());
	}

	/**
	 * Set value of BrokerHost
	 * @param brokerhost
	 */
	public final void setBrokerHost(java.lang.String brokerhost)
	{
		setBrokerHost(getContext(), brokerhost);
	}

	/**
	 * Set value of BrokerHost
	 * @param context
	 * @param brokerhost
	 */
	public final void setBrokerHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brokerhost)
	{
		getMendixObject().setValue(context, MemberNames.BrokerHost.toString(), brokerhost);
	}

	/**
	 * @return value of BrokerPort
	 */
	public final java.lang.Integer getBrokerPort()
	{
		return getBrokerPort(getContext());
	}

	/**
	 * @param context
	 * @return value of BrokerPort
	 */
	public final java.lang.Integer getBrokerPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BrokerPort.toString());
	}

	/**
	 * Set value of BrokerPort
	 * @param brokerport
	 */
	public final void setBrokerPort(java.lang.Integer brokerport)
	{
		setBrokerPort(getContext(), brokerport);
	}

	/**
	 * Set value of BrokerPort
	 * @param context
	 * @param brokerport
	 */
	public final void setBrokerPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer brokerport)
	{
		getMendixObject().setValue(context, MemberNames.BrokerPort.toString(), brokerport);
	}

	/**
	 * @return value of TimeOut
	 */
	public final java.lang.Integer getTimeOut()
	{
		return getTimeOut(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeOut
	 */
	public final java.lang.Integer getTimeOut(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TimeOut.toString());
	}

	/**
	 * Set value of TimeOut
	 * @param timeout
	 */
	public final void setTimeOut(java.lang.Integer timeout)
	{
		setTimeOut(getContext(), timeout);
	}

	/**
	 * Set value of TimeOut
	 * @param context
	 * @param timeout
	 */
	public final void setTimeOut(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timeout)
	{
		getMendixObject().setValue(context, MemberNames.TimeOut.toString(), timeout);
	}

	/**
	 * @return value of SSL
	 */
	public final java.lang.Boolean getSSL()
	{
		return getSSL(getContext());
	}

	/**
	 * @param context
	 * @return value of SSL
	 */
	public final java.lang.Boolean getSSL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SSL.toString());
	}

	/**
	 * Set value of SSL
	 * @param ssl
	 */
	public final void setSSL(java.lang.Boolean ssl)
	{
		setSSL(getContext(), ssl);
	}

	/**
	 * Set value of SSL
	 * @param context
	 * @param ssl
	 */
	public final void setSSL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ssl)
	{
		getMendixObject().setValue(context, MemberNames.SSL.toString(), ssl);
	}

	/**
	 * @return value of KeepAliveTime
	 */
	public final java.lang.Integer getKeepAliveTime()
	{
		return getKeepAliveTime(getContext());
	}

	/**
	 * @param context
	 * @return value of KeepAliveTime
	 */
	public final java.lang.Integer getKeepAliveTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.KeepAliveTime.toString());
	}

	/**
	 * Set value of KeepAliveTime
	 * @param keepalivetime
	 */
	public final void setKeepAliveTime(java.lang.Integer keepalivetime)
	{
		setKeepAliveTime(getContext(), keepalivetime);
	}

	/**
	 * Set value of KeepAliveTime
	 * @param context
	 * @param keepalivetime
	 */
	public final void setKeepAliveTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer keepalivetime)
	{
		getMendixObject().setValue(context, MemberNames.KeepAliveTime.toString(), keepalivetime);
	}

	/**
	 * @return value of CleanSession
	 */
	public final java.lang.Boolean getCleanSession()
	{
		return getCleanSession(getContext());
	}

	/**
	 * @param context
	 * @return value of CleanSession
	 */
	public final java.lang.Boolean getCleanSession(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CleanSession.toString());
	}

	/**
	 * Set value of CleanSession
	 * @param cleansession
	 */
	public final void setCleanSession(java.lang.Boolean cleansession)
	{
		setCleanSession(getContext(), cleansession);
	}

	/**
	 * Set value of CleanSession
	 * @param context
	 * @param cleansession
	 */
	public final void setCleanSession(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cleansession)
	{
		getMendixObject().setValue(context, MemberNames.CleanSession.toString(), cleansession);
	}

	/**
	 * @return value of AutoReconnect
	 */
	public final java.lang.Boolean getAutoReconnect()
	{
		return getAutoReconnect(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoReconnect
	 */
	public final java.lang.Boolean getAutoReconnect(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoReconnect.toString());
	}

	/**
	 * Set value of AutoReconnect
	 * @param autoreconnect
	 */
	public final void setAutoReconnect(java.lang.Boolean autoreconnect)
	{
		setAutoReconnect(getContext(), autoreconnect);
	}

	/**
	 * Set value of AutoReconnect
	 * @param context
	 * @param autoreconnect
	 */
	public final void setAutoReconnect(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autoreconnect)
	{
		getMendixObject().setValue(context, MemberNames.AutoReconnect.toString(), autoreconnect);
	}

	/**
	 * @return value of CA
	 */
	public final java.lang.String getCA()
	{
		return getCA(getContext());
	}

	/**
	 * @param context
	 * @return value of CA
	 */
	public final java.lang.String getCA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CA.toString());
	}

	/**
	 * Set value of CA
	 * @param ca
	 */
	public final void setCA(java.lang.String ca)
	{
		setCA(getContext(), ca);
	}

	/**
	 * Set value of CA
	 * @param context
	 * @param ca
	 */
	public final void setCA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ca)
	{
		getMendixObject().setValue(context, MemberNames.CA.toString(), ca);
	}

	/**
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey()
	{
		return getClientKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientKey.toString());
	}

	/**
	 * Set value of ClientKey
	 * @param clientkey
	 */
	public final void setClientKey(java.lang.String clientkey)
	{
		setClientKey(getContext(), clientkey);
	}

	/**
	 * Set value of ClientKey
	 * @param context
	 * @param clientkey
	 */
	public final void setClientKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientkey)
	{
		getMendixObject().setValue(context, MemberNames.ClientKey.toString(), clientkey);
	}

	/**
	 * @return value of ClientCertificate
	 */
	public final java.lang.String getClientCertificate()
	{
		return getClientCertificate(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientCertificate
	 */
	public final java.lang.String getClientCertificate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientCertificate.toString());
	}

	/**
	 * Set value of ClientCertificate
	 * @param clientcertificate
	 */
	public final void setClientCertificate(java.lang.String clientcertificate)
	{
		setClientCertificate(getContext(), clientcertificate);
	}

	/**
	 * Set value of ClientCertificate
	 * @param context
	 * @param clientcertificate
	 */
	public final void setClientCertificate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientcertificate)
	{
		getMendixObject().setValue(context, MemberNames.ClientCertificate.toString(), clientcertificate);
	}

	/**
	 * @return value of CertificatePassword
	 */
	public final java.lang.String getCertificatePassword()
	{
		return getCertificatePassword(getContext());
	}

	/**
	 * @param context
	 * @return value of CertificatePassword
	 */
	public final java.lang.String getCertificatePassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CertificatePassword.toString());
	}

	/**
	 * Set value of CertificatePassword
	 * @param certificatepassword
	 */
	public final void setCertificatePassword(java.lang.String certificatepassword)
	{
		setCertificatePassword(getContext(), certificatepassword);
	}

	/**
	 * Set value of CertificatePassword
	 * @param context
	 * @param certificatepassword
	 */
	public final void setCertificatePassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String certificatepassword)
	{
		getMendixObject().setValue(context, MemberNames.CertificatePassword.toString(), certificatepassword);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * Get value of AuthenticationMethod
	 * @param authenticationmethod
	 */
	public final mqttconnector.proxies.AuthenticationMethod getAuthenticationMethod()
	{
		return getAuthenticationMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthenticationMethod
	 */
	public final mqttconnector.proxies.AuthenticationMethod getAuthenticationMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AuthenticationMethod.toString());
		if (obj == null) {
			return null;
		}
		return mqttconnector.proxies.AuthenticationMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AuthenticationMethod
	 * @param authenticationmethod
	 */
	public final void setAuthenticationMethod(mqttconnector.proxies.AuthenticationMethod authenticationmethod)
	{
		setAuthenticationMethod(getContext(), authenticationmethod);
	}

	/**
	 * Set value of AuthenticationMethod
	 * @param context
	 * @param authenticationmethod
	 */
	public final void setAuthenticationMethod(com.mendix.systemwideinterfaces.core.IContext context, mqttconnector.proxies.AuthenticationMethod authenticationmethod)
	{
		if (authenticationmethod != null) {
			getMendixObject().setValue(context, MemberNames.AuthenticationMethod.toString(), authenticationmethod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AuthenticationMethod.toString(), null);
		}
	}

	/**
	 * @return value of AdvancedSettingsToggle
	 */
	public final java.lang.Boolean getAdvancedSettingsToggle()
	{
		return getAdvancedSettingsToggle(getContext());
	}

	/**
	 * @param context
	 * @return value of AdvancedSettingsToggle
	 */
	public final java.lang.Boolean getAdvancedSettingsToggle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AdvancedSettingsToggle.toString());
	}

	/**
	 * Set value of AdvancedSettingsToggle
	 * @param advancedsettingstoggle
	 */
	public final void setAdvancedSettingsToggle(java.lang.Boolean advancedsettingstoggle)
	{
		setAdvancedSettingsToggle(getContext(), advancedsettingstoggle);
	}

	/**
	 * Set value of AdvancedSettingsToggle
	 * @param context
	 * @param advancedsettingstoggle
	 */
	public final void setAdvancedSettingsToggle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean advancedsettingstoggle)
	{
		getMendixObject().setValue(context, MemberNames.AdvancedSettingsToggle.toString(), advancedsettingstoggle);
	}

	/**
	 * @return value of HostnameVerification
	 */
	public final java.lang.Boolean getHostnameVerification()
	{
		return getHostnameVerification(getContext());
	}

	/**
	 * @param context
	 * @return value of HostnameVerification
	 */
	public final java.lang.Boolean getHostnameVerification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HostnameVerification.toString());
	}

	/**
	 * Set value of HostnameVerification
	 * @param hostnameverification
	 */
	public final void setHostnameVerification(java.lang.Boolean hostnameverification)
	{
		setHostnameVerification(getContext(), hostnameverification);
	}

	/**
	 * Set value of HostnameVerification
	 * @param context
	 * @param hostnameverification
	 */
	public final void setHostnameVerification(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hostnameverification)
	{
		getMendixObject().setValue(context, MemberNames.HostnameVerification.toString(), hostnameverification);
	}

	/**
	 * @return value of MaxInFlight
	 */
	public final java.lang.Integer getMaxInFlight()
	{
		return getMaxInFlight(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxInFlight
	 */
	public final java.lang.Integer getMaxInFlight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxInFlight.toString());
	}

	/**
	 * Set value of MaxInFlight
	 * @param maxinflight
	 */
	public final void setMaxInFlight(java.lang.Integer maxinflight)
	{
		setMaxInFlight(getContext(), maxinflight);
	}

	/**
	 * Set value of MaxInFlight
	 * @param context
	 * @param maxinflight
	 */
	public final void setMaxInFlight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxinflight)
	{
		getMendixObject().setValue(context, MemberNames.MaxInFlight.toString(), maxinflight);
	}

	/**
	 * @return value of MaxReconnectDelay
	 */
	public final java.lang.Integer getMaxReconnectDelay()
	{
		return getMaxReconnectDelay(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxReconnectDelay
	 */
	public final java.lang.Integer getMaxReconnectDelay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxReconnectDelay.toString());
	}

	/**
	 * Set value of MaxReconnectDelay
	 * @param maxreconnectdelay
	 */
	public final void setMaxReconnectDelay(java.lang.Integer maxreconnectdelay)
	{
		setMaxReconnectDelay(getContext(), maxreconnectdelay);
	}

	/**
	 * Set value of MaxReconnectDelay
	 * @param context
	 * @param maxreconnectdelay
	 */
	public final void setMaxReconnectDelay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxreconnectdelay)
	{
		getMendixObject().setValue(context, MemberNames.MaxReconnectDelay.toString(), maxreconnectdelay);
	}

	/**
	 * @return value of SetWill
	 */
	public final java.lang.Boolean getSetWill()
	{
		return getSetWill(getContext());
	}

	/**
	 * @param context
	 * @return value of SetWill
	 */
	public final java.lang.Boolean getSetWill(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SetWill.toString());
	}

	/**
	 * Set value of SetWill
	 * @param setwill
	 */
	public final void setSetWill(java.lang.Boolean setwill)
	{
		setSetWill(getContext(), setwill);
	}

	/**
	 * Set value of SetWill
	 * @param context
	 * @param setwill
	 */
	public final void setSetWill(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean setwill)
	{
		getMendixObject().setValue(context, MemberNames.SetWill.toString(), setwill);
	}

	/**
	 * @return value of WillTopic
	 */
	public final java.lang.String getWillTopic()
	{
		return getWillTopic(getContext());
	}

	/**
	 * @param context
	 * @return value of WillTopic
	 */
	public final java.lang.String getWillTopic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WillTopic.toString());
	}

	/**
	 * Set value of WillTopic
	 * @param willtopic
	 */
	public final void setWillTopic(java.lang.String willtopic)
	{
		setWillTopic(getContext(), willtopic);
	}

	/**
	 * Set value of WillTopic
	 * @param context
	 * @param willtopic
	 */
	public final void setWillTopic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String willtopic)
	{
		getMendixObject().setValue(context, MemberNames.WillTopic.toString(), willtopic);
	}

	/**
	 * @return value of WillPayLoad
	 */
	public final java.lang.String getWillPayLoad()
	{
		return getWillPayLoad(getContext());
	}

	/**
	 * @param context
	 * @return value of WillPayLoad
	 */
	public final java.lang.String getWillPayLoad(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WillPayLoad.toString());
	}

	/**
	 * Set value of WillPayLoad
	 * @param willpayload
	 */
	public final void setWillPayLoad(java.lang.String willpayload)
	{
		setWillPayLoad(getContext(), willpayload);
	}

	/**
	 * Set value of WillPayLoad
	 * @param context
	 * @param willpayload
	 */
	public final void setWillPayLoad(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String willpayload)
	{
		getMendixObject().setValue(context, MemberNames.WillPayLoad.toString(), willpayload);
	}

	/**
	 * Get value of WillQoS
	 * @param willqos
	 */
	public final mqttconnector.proxies.QoS getWillQoS()
	{
		return getWillQoS(getContext());
	}

	/**
	 * @param context
	 * @return value of WillQoS
	 */
	public final mqttconnector.proxies.QoS getWillQoS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WillQoS.toString());
		if (obj == null) {
			return null;
		}
		return mqttconnector.proxies.QoS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WillQoS
	 * @param willqos
	 */
	public final void setWillQoS(mqttconnector.proxies.QoS willqos)
	{
		setWillQoS(getContext(), willqos);
	}

	/**
	 * Set value of WillQoS
	 * @param context
	 * @param willqos
	 */
	public final void setWillQoS(com.mendix.systemwideinterfaces.core.IContext context, mqttconnector.proxies.QoS willqos)
	{
		if (willqos != null) {
			getMendixObject().setValue(context, MemberNames.WillQoS.toString(), willqos.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.WillQoS.toString(), null);
		}
	}

	/**
	 * @return value of WillRetain
	 */
	public final java.lang.Boolean getWillRetain()
	{
		return getWillRetain(getContext());
	}

	/**
	 * @param context
	 * @return value of WillRetain
	 */
	public final java.lang.Boolean getWillRetain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WillRetain.toString());
	}

	/**
	 * Set value of WillRetain
	 * @param willretain
	 */
	public final void setWillRetain(java.lang.Boolean willretain)
	{
		setWillRetain(getContext(), willretain);
	}

	/**
	 * Set value of WillRetain
	 * @param context
	 * @param willretain
	 */
	public final void setWillRetain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean willretain)
	{
		getMendixObject().setValue(context, MemberNames.WillRetain.toString(), willretain);
	}

	/**
	 * @return value of OperationTimeout
	 */
	public final java.lang.Integer getOperationTimeout()
	{
		return getOperationTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of OperationTimeout
	 */
	public final java.lang.Integer getOperationTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OperationTimeout.toString());
	}

	/**
	 * Set value of OperationTimeout
	 * @param operationtimeout
	 */
	public final void setOperationTimeout(java.lang.Integer operationtimeout)
	{
		setOperationTimeout(getContext(), operationtimeout);
	}

	/**
	 * Set value of OperationTimeout
	 * @param context
	 * @param operationtimeout
	 */
	public final void setOperationTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer operationtimeout)
	{
		getMendixObject().setValue(context, MemberNames.OperationTimeout.toString(), operationtimeout);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return connectionDetailMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mqttconnector.proxies.ConnectionDetail that = (mqttconnector.proxies.ConnectionDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
