// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttconnector.proxies;

public class ValidationError implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject validationErrorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MqttConnector.ValidationError";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Error("Error"),
		ValidationError_ConnectionDetail("MqttConnector.ValidationError_ConnectionDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ValidationError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ValidationError(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject validationErrorMendixObject)
	{
		if (validationErrorMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, validationErrorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.validationErrorMendixObject = validationErrorMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mqttconnector.proxies.ValidationError initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mqttconnector.proxies.ValidationError(context, mendixObject);
	}

	public static mqttconnector.proxies.ValidationError load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mqttconnector.proxies.ValidationError.initialize(context, mendixObject);
	}

	/**
	 * @return value of Error
	 */
	public final java.lang.String getError()
	{
		return getError(getContext());
	}

	/**
	 * @param context
	 * @return value of Error
	 */
	public final java.lang.String getError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Error.toString());
	}

	/**
	 * Set value of Error
	 * @param error
	 */
	public final void setError(java.lang.String error)
	{
		setError(getContext(), error);
	}

	/**
	 * Set value of Error
	 * @param context
	 * @param error
	 */
	public final void setError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String error)
	{
		getMendixObject().setValue(context, MemberNames.Error.toString(), error);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ValidationError_ConnectionDetail
	 */
	public final mqttconnector.proxies.ConnectionDetail getValidationError_ConnectionDetail() throws com.mendix.core.CoreException
	{
		return getValidationError_ConnectionDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidationError_ConnectionDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final mqttconnector.proxies.ConnectionDetail getValidationError_ConnectionDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mqttconnector.proxies.ConnectionDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ValidationError_ConnectionDetail.toString());
		if (identifier != null) {
			result = mqttconnector.proxies.ConnectionDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ValidationError_ConnectionDetail
	 * @param validationerror_connectiondetail
	 */
	public final void setValidationError_ConnectionDetail(mqttconnector.proxies.ConnectionDetail validationerror_connectiondetail)
	{
		setValidationError_ConnectionDetail(getContext(), validationerror_connectiondetail);
	}

	/**
	 * Set value of ValidationError_ConnectionDetail
	 * @param context
	 * @param validationerror_connectiondetail
	 */
	public final void setValidationError_ConnectionDetail(com.mendix.systemwideinterfaces.core.IContext context, mqttconnector.proxies.ConnectionDetail validationerror_connectiondetail)
	{
		if (validationerror_connectiondetail == null) {
			getMendixObject().setValue(context, MemberNames.ValidationError_ConnectionDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ValidationError_ConnectionDetail.toString(), validationerror_connectiondetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return validationErrorMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mqttconnector.proxies.ValidationError that = (mqttconnector.proxies.ValidationError) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
