// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administrationmanagement.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the AdministrationManagement module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Request_StatusApprovedBuilder(
		usermanagement.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AdministrationManagement.ACT_Request_StatusApproved");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Request_StatusApproved(
		IContext context,
		usermanagement.proxies.Registration _registration
	)
	{
		aCT_Request_StatusApprovedBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Request_StatusRejectedBuilder(
		usermanagement.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AdministrationManagement.ACT_Request_StatusRejected");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Request_StatusRejected(
		IContext context,
		usermanagement.proxies.Registration _registration
	)
	{
		aCT_Request_StatusRejectedBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Registration_GetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AdministrationManagement.DS_Registration_Get");
		return builder;
	}

	public static java.util.List<usermanagement.proxies.Registration> dS_Registration_Get(IContext context)
	{
		Object result = dS_Registration_GetBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usermanagement.proxies.Registration.initialize(context, obj));
	}
}
