// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restconsume.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the RESTConsume module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createInputBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("RESTConsume.CreateInput");
		return builder;
	}

	public static restconsume.proxies.Input createInput(IContext context)
	{
		Object result = createInputBuilder().execute(context);
		return result == null ? null : restconsume.proxies.Input.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder microflowBuilder(
		restconsume.proxies.Input _input
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("RESTConsume.Microflow");
		builder = builder.withParam("Input", _input);
		return builder;
	}

	public static void microflow(
		IContext context,
		restconsume.proxies.Input _input
	)
	{
		microflowBuilder(
				_input
			)
			.execute(context);
	}
}
