// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package calendarevents.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CalendarEvents module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Calendar_RetrieveEventsBuilder(
		calendarevents.proxies.Calendar _calendar
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CalendarEvents.ACT_Calendar_RetrieveEvents");
		builder = builder.withParam("Calendar", _calendar);
		return builder;
	}

	public static java.util.List<calendarevents.proxies.Calendar> aCT_Calendar_RetrieveEvents(
		IContext context,
		calendarevents.proxies.Calendar _calendar
	)
	{
		Object result = aCT_Calendar_RetrieveEventsBuilder(
				_calendar
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> calendarevents.proxies.Calendar.initialize(context, obj));
	}
}
