// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package calendarevents.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CalendarEvents module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Booking_SaveBuilder(
		calendarevents.proxies.Booking _booking,
		rooms.proxies.Room _room
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CalendarEvents.ACT_Booking_Save");
		builder = builder.withParam("Booking", _booking);
		builder = builder.withParam("Room", _room);
		return builder;
	}

	public static void aCT_Booking_Save(
		IContext context,
		calendarevents.proxies.Booking _booking,
		rooms.proxies.Room _room
	)
	{
		aCT_Booking_SaveBuilder(
				_booking,
				_room
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Calendar_EditBuilder(
		calendarevents.proxies.Calendar _calendar
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CalendarEvents.ACT_Calendar_Edit");
		builder = builder.withParam("Calendar", _calendar);
		return builder;
	}

	public static void aCT_Calendar_Edit(
		IContext context,
		calendarevents.proxies.Calendar _calendar
	)
	{
		aCT_Calendar_EditBuilder(
				_calendar
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Calendar_MovingBuilder(
		calendarevents.proxies.Calendar _calendar
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CalendarEvents.ACT_Calendar_Moving");
		builder = builder.withParam("Calendar", _calendar);
		return builder;
	}

	public static void aCT_Calendar_Moving(
		IContext context,
		calendarevents.proxies.Calendar _calendar
	)
	{
		aCT_Calendar_MovingBuilder(
				_calendar
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Calendar_RetrieveEventsBuilder(
		calendarevents.proxies.Calendar _calendar
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CalendarEvents.ACT_Calendar_RetrieveEvents");
		builder = builder.withParam("Calendar", _calendar);
		return builder;
	}

	public static java.util.List<calendarevents.proxies.Calendar> aCT_Calendar_RetrieveEvents(
		IContext context,
		calendarevents.proxies.Calendar _calendar
	)
	{
		Object result = aCT_Calendar_RetrieveEventsBuilder(
				_calendar
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> calendarevents.proxies.Calendar.initialize(context, obj));
	}
}
