// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vacationmanagement.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the VacationManagement module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_VacationRequest_ApproveBuilder(
		vacationmanagement.proxies.VacationRequest _vacationRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("VacationManagement.ACT_VacationRequest_Approve");
		builder = builder.withParam("VacationRequest", _vacationRequest);
		return builder;
	}

	public static void aCT_VacationRequest_Approve(
		IContext context,
		vacationmanagement.proxies.VacationRequest _vacationRequest
	)
	{
		aCT_VacationRequest_ApproveBuilder(
				_vacationRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_VacationRequest_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("VacationManagement.ACT_VacationRequest_Create");
		return builder;
	}

	public static void aCT_VacationRequest_Create(IContext context)
	{
		aCT_VacationRequest_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_VacationRequest_SubmitBuilder(
		vacationmanagement.proxies.VacationRequest _vacationRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("VacationManagement.ACT_VacationRequest_Submit");
		builder = builder.withParam("VacationRequest", _vacationRequest);
		return builder;
	}

	public static void aCT_VacationRequest_Submit(
		IContext context,
		vacationmanagement.proxies.VacationRequest _vacationRequest
	)
	{
		aCT_VacationRequest_SubmitBuilder(
				_vacationRequest
			)
			.execute(context);
	}
}
