// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package carfinder.proxies;

public class Ad implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject adMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CarFinder.Ad";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AdId("AdId"),
		Title("Title"),
		Description("Description"),
		PostingDate("PostingDate"),
		Category("Category"),
		Ad_Motorcycle("CarFinder.Ad_Motorcycle"),
		Ad_Truck("CarFinder.Ad_Truck"),
		Ad_Car("CarFinder.Ad_Car");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ad(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ad(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adMendixObject)
	{
		if (adMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, adMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.adMendixObject = adMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static carfinder.proxies.Ad initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new carfinder.proxies.Ad(context, mendixObject);
	}

	public static carfinder.proxies.Ad load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return carfinder.proxies.Ad.initialize(context, mendixObject);
	}

	public static java.util.List<carfinder.proxies.Ad> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> carfinder.proxies.Ad.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AdId
	 */
	public final java.lang.Long getAdId()
	{
		return getAdId(getContext());
	}

	/**
	 * @param context
	 * @return value of AdId
	 */
	public final java.lang.Long getAdId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AdId.toString());
	}

	/**
	 * Set value of AdId
	 * @param adid
	 */
	public final void setAdId(java.lang.Long adid)
	{
		setAdId(getContext(), adid);
	}

	/**
	 * Set value of AdId
	 * @param context
	 * @param adid
	 */
	public final void setAdId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long adid)
	{
		getMendixObject().setValue(context, MemberNames.AdId.toString(), adid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of PostingDate
	 */
	public final java.util.Date getPostingDate()
	{
		return getPostingDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PostingDate
	 */
	public final java.util.Date getPostingDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostingDate.toString());
	}

	/**
	 * Set value of PostingDate
	 * @param postingdate
	 */
	public final void setPostingDate(java.util.Date postingdate)
	{
		setPostingDate(getContext(), postingdate);
	}

	/**
	 * Set value of PostingDate
	 * @param context
	 * @param postingdate
	 */
	public final void setPostingDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postingdate)
	{
		getMendixObject().setValue(context, MemberNames.PostingDate.toString(), postingdate);
	}

	/**
	 * Get value of Category
	 * @param category
	 */
	public final carfinder.proxies.ENUM_Ad_Category getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final carfinder.proxies.ENUM_Ad_Category getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Category.toString());
		if (obj == null) {
			return null;
		}
		return carfinder.proxies.ENUM_Ad_Category.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(carfinder.proxies.ENUM_Ad_Category category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, carfinder.proxies.ENUM_Ad_Category category)
	{
		if (category != null) {
			getMendixObject().setValue(context, MemberNames.Category.toString(), category.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Category.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ad_Motorcycle
	 */
	public final carfinder.proxies.Motorcycle getAd_Motorcycle() throws com.mendix.core.CoreException
	{
		return getAd_Motorcycle(getContext());
	}

	/**
	 * @param context
	 * @return value of Ad_Motorcycle
	 * @throws com.mendix.core.CoreException
	 */
	public final carfinder.proxies.Motorcycle getAd_Motorcycle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		carfinder.proxies.Motorcycle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ad_Motorcycle.toString());
		if (identifier != null) {
			result = carfinder.proxies.Motorcycle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ad_Motorcycle
	 * @param ad_motorcycle
	 */
	public final void setAd_Motorcycle(carfinder.proxies.Motorcycle ad_motorcycle)
	{
		setAd_Motorcycle(getContext(), ad_motorcycle);
	}

	/**
	 * Set value of Ad_Motorcycle
	 * @param context
	 * @param ad_motorcycle
	 */
	public final void setAd_Motorcycle(com.mendix.systemwideinterfaces.core.IContext context, carfinder.proxies.Motorcycle ad_motorcycle)
	{
		if (ad_motorcycle == null) {
			getMendixObject().setValue(context, MemberNames.Ad_Motorcycle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ad_Motorcycle.toString(), ad_motorcycle.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ad_Truck
	 */
	public final carfinder.proxies.Truck getAd_Truck() throws com.mendix.core.CoreException
	{
		return getAd_Truck(getContext());
	}

	/**
	 * @param context
	 * @return value of Ad_Truck
	 * @throws com.mendix.core.CoreException
	 */
	public final carfinder.proxies.Truck getAd_Truck(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		carfinder.proxies.Truck result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ad_Truck.toString());
		if (identifier != null) {
			result = carfinder.proxies.Truck.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ad_Truck
	 * @param ad_truck
	 */
	public final void setAd_Truck(carfinder.proxies.Truck ad_truck)
	{
		setAd_Truck(getContext(), ad_truck);
	}

	/**
	 * Set value of Ad_Truck
	 * @param context
	 * @param ad_truck
	 */
	public final void setAd_Truck(com.mendix.systemwideinterfaces.core.IContext context, carfinder.proxies.Truck ad_truck)
	{
		if (ad_truck == null) {
			getMendixObject().setValue(context, MemberNames.Ad_Truck.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ad_Truck.toString(), ad_truck.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ad_Car
	 */
	public final carfinder.proxies.Car getAd_Car() throws com.mendix.core.CoreException
	{
		return getAd_Car(getContext());
	}

	/**
	 * @param context
	 * @return value of Ad_Car
	 * @throws com.mendix.core.CoreException
	 */
	public final carfinder.proxies.Car getAd_Car(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		carfinder.proxies.Car result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ad_Car.toString());
		if (identifier != null) {
			result = carfinder.proxies.Car.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ad_Car
	 * @param ad_car
	 */
	public final void setAd_Car(carfinder.proxies.Car ad_car)
	{
		setAd_Car(getContext(), ad_car);
	}

	/**
	 * Set value of Ad_Car
	 * @param context
	 * @param ad_car
	 */
	public final void setAd_Car(com.mendix.systemwideinterfaces.core.IContext context, carfinder.proxies.Car ad_car)
	{
		if (ad_car == null) {
			getMendixObject().setValue(context, MemberNames.Ad_Car.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ad_Car.toString(), ad_car.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return adMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final carfinder.proxies.Ad that = (carfinder.proxies.Ad) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
