// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package carfinder.proxies;

public class AdImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CarFinder.AdImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		AdImage_Ad("CarFinder.AdImage_Ad");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AdImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adImageMendixObject)
	{
		super(context, adImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, adImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static carfinder.proxies.AdImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new carfinder.proxies.AdImage(context, mendixObject);
	}

	public static carfinder.proxies.AdImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return carfinder.proxies.AdImage.initialize(context, mendixObject);
	}

	public static java.util.List<carfinder.proxies.AdImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> carfinder.proxies.AdImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AdImage_Ad
	 */
	public final carfinder.proxies.Ad getAdImage_Ad() throws com.mendix.core.CoreException
	{
		return getAdImage_Ad(getContext());
	}

	/**
	 * @param context
	 * @return value of AdImage_Ad
	 * @throws com.mendix.core.CoreException
	 */
	public final carfinder.proxies.Ad getAdImage_Ad(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		carfinder.proxies.Ad result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AdImage_Ad.toString());
		if (identifier != null) {
			result = carfinder.proxies.Ad.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AdImage_Ad
	 * @param adimage_ad
	 */
	public final void setAdImage_Ad(carfinder.proxies.Ad adimage_ad)
	{
		setAdImage_Ad(getContext(), adimage_ad);
	}

	/**
	 * Set value of AdImage_Ad
	 * @param context
	 * @param adimage_ad
	 */
	public final void setAdImage_Ad(com.mendix.systemwideinterfaces.core.IContext context, carfinder.proxies.Ad adimage_ad)
	{
		if (adimage_ad == null) {
			getMendixObject().setValue(context, MemberNames.AdImage_Ad.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AdImage_Ad.toString(), adimage_ad.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final carfinder.proxies.AdImage that = (carfinder.proxies.AdImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
