// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Category_SaveBuilder(
		myfirstmodule.proxies.Category _category
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Category_Save");
		builder = builder.withParam("Category", _category);
		return builder;
	}

	public static void aCT_Category_Save(
		IContext context,
		myfirstmodule.proxies.Category _category
	)
	{
		aCT_Category_SaveBuilder(
				_category
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Transaction_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Transaction_Create");
		return builder;
	}

	public static void aCT_Transaction_Create(IContext context)
	{
		aCT_Transaction_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Transaction_EditBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Transaction_Edit");
		return builder;
	}

	public static void aCT_Transaction_Edit(IContext context)
	{
		aCT_Transaction_EditBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Category_ValidateBuilder(
		myfirstmodule.proxies.Category _category
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SUB_Category_Validate");
		builder = builder.withParam("Category", _category);
		return builder;
	}

	public static boolean sUB_Category_Validate(
		IContext context,
		myfirstmodule.proxies.Category _category
	)
	{
		Object result = sUB_Category_ValidateBuilder(
				_category
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_RegistrationBuilder(
		myfirstmodule.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.VAL_Registration");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static boolean vAL_Registration(
		IContext context,
		myfirstmodule.proxies.Registration _registration
	)
	{
		Object result = vAL_RegistrationBuilder(
				_registration
			)
			.execute(context);
		return (boolean) result;
	}
}
