// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package calendarevents.proxies;

public class AllowedConferenceSolutionType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject allowedConferenceSolutionTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CalendarEvents.AllowedConferenceSolutionType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		AllowedConferenceSolutionType_AllowedConferenceSolutionTypes("CalendarEvents.AllowedConferenceSolutionType_AllowedConferenceSolutionTypes");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AllowedConferenceSolutionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AllowedConferenceSolutionType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject allowedConferenceSolutionTypeMendixObject)
	{
		if (allowedConferenceSolutionTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, allowedConferenceSolutionTypeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.allowedConferenceSolutionTypeMendixObject = allowedConferenceSolutionTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static calendarevents.proxies.AllowedConferenceSolutionType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new calendarevents.proxies.AllowedConferenceSolutionType(context, mendixObject);
	}

	public static calendarevents.proxies.AllowedConferenceSolutionType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return calendarevents.proxies.AllowedConferenceSolutionType.initialize(context, mendixObject);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AllowedConferenceSolutionType_AllowedConferenceSolutionTypes
	 */
	public final calendarevents.proxies.AllowedConferenceSolutionTypes getAllowedConferenceSolutionType_AllowedConferenceSolutionTypes() throws com.mendix.core.CoreException
	{
		return getAllowedConferenceSolutionType_AllowedConferenceSolutionTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowedConferenceSolutionType_AllowedConferenceSolutionTypes
	 * @throws com.mendix.core.CoreException
	 */
	public final calendarevents.proxies.AllowedConferenceSolutionTypes getAllowedConferenceSolutionType_AllowedConferenceSolutionTypes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		calendarevents.proxies.AllowedConferenceSolutionTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AllowedConferenceSolutionType_AllowedConferenceSolutionTypes.toString());
		if (identifier != null) {
			result = calendarevents.proxies.AllowedConferenceSolutionTypes.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AllowedConferenceSolutionType_AllowedConferenceSolutionTypes
	 * @param allowedconferencesolutiontype_allowedconferencesolutiontypes
	 */
	public final void setAllowedConferenceSolutionType_AllowedConferenceSolutionTypes(calendarevents.proxies.AllowedConferenceSolutionTypes allowedconferencesolutiontype_allowedconferencesolutiontypes)
	{
		setAllowedConferenceSolutionType_AllowedConferenceSolutionTypes(getContext(), allowedconferencesolutiontype_allowedconferencesolutiontypes);
	}

	/**
	 * Set value of AllowedConferenceSolutionType_AllowedConferenceSolutionTypes
	 * @param context
	 * @param allowedconferencesolutiontype_allowedconferencesolutiontypes
	 */
	public final void setAllowedConferenceSolutionType_AllowedConferenceSolutionTypes(com.mendix.systemwideinterfaces.core.IContext context, calendarevents.proxies.AllowedConferenceSolutionTypes allowedconferencesolutiontype_allowedconferencesolutiontypes)
	{
		if (allowedconferencesolutiontype_allowedconferencesolutiontypes == null) {
			getMendixObject().setValue(context, MemberNames.AllowedConferenceSolutionType_AllowedConferenceSolutionTypes.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AllowedConferenceSolutionType_AllowedConferenceSolutionTypes.toString(), allowedconferencesolutiontype_allowedconferencesolutiontypes.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return allowedConferenceSolutionTypeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final calendarevents.proxies.AllowedConferenceSolutionType that = (calendarevents.proxies.AllowedConferenceSolutionType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
