// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package calendarevents.proxies;

public class AllowedConferenceSolutionTypes implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject allowedConferenceSolutionTypesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CalendarEvents.AllowedConferenceSolutionTypes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AllowedConferenceSolutionTypes_ConferenceProperties("CalendarEvents.AllowedConferenceSolutionTypes_ConferenceProperties");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AllowedConferenceSolutionTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AllowedConferenceSolutionTypes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject allowedConferenceSolutionTypesMendixObject)
	{
		if (allowedConferenceSolutionTypesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, allowedConferenceSolutionTypesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.allowedConferenceSolutionTypesMendixObject = allowedConferenceSolutionTypesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static calendarevents.proxies.AllowedConferenceSolutionTypes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new calendarevents.proxies.AllowedConferenceSolutionTypes(context, mendixObject);
	}

	public static calendarevents.proxies.AllowedConferenceSolutionTypes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return calendarevents.proxies.AllowedConferenceSolutionTypes.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AllowedConferenceSolutionTypes_ConferenceProperties
	 */
	public final calendarevents.proxies.ConferenceProperties getAllowedConferenceSolutionTypes_ConferenceProperties() throws com.mendix.core.CoreException
	{
		return getAllowedConferenceSolutionTypes_ConferenceProperties(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowedConferenceSolutionTypes_ConferenceProperties
	 * @throws com.mendix.core.CoreException
	 */
	public final calendarevents.proxies.ConferenceProperties getAllowedConferenceSolutionTypes_ConferenceProperties(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		calendarevents.proxies.ConferenceProperties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AllowedConferenceSolutionTypes_ConferenceProperties.toString());
		if (identifier != null) {
			result = calendarevents.proxies.ConferenceProperties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AllowedConferenceSolutionTypes_ConferenceProperties
	 * @param allowedconferencesolutiontypes_conferenceproperties
	 */
	public final void setAllowedConferenceSolutionTypes_ConferenceProperties(calendarevents.proxies.ConferenceProperties allowedconferencesolutiontypes_conferenceproperties)
	{
		setAllowedConferenceSolutionTypes_ConferenceProperties(getContext(), allowedconferencesolutiontypes_conferenceproperties);
	}

	/**
	 * Set value of AllowedConferenceSolutionTypes_ConferenceProperties
	 * @param context
	 * @param allowedconferencesolutiontypes_conferenceproperties
	 */
	public final void setAllowedConferenceSolutionTypes_ConferenceProperties(com.mendix.systemwideinterfaces.core.IContext context, calendarevents.proxies.ConferenceProperties allowedconferencesolutiontypes_conferenceproperties)
	{
		if (allowedconferencesolutiontypes_conferenceproperties == null) {
			getMendixObject().setValue(context, MemberNames.AllowedConferenceSolutionTypes_ConferenceProperties.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AllowedConferenceSolutionTypes_ConferenceProperties.toString(), allowedconferencesolutiontypes_conferenceproperties.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return allowedConferenceSolutionTypesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final calendarevents.proxies.AllowedConferenceSolutionTypes that = (calendarevents.proxies.AllowedConferenceSolutionTypes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
