// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package calendarevents.proxies;

public class Summary implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CalendarEvents.Summary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Kind("Kind"),
		Etag("Etag"),
		_id("_id"),
		Summary("Summary"),
		TimeZone("TimeZone"),
		ConferenceProperties_Summary("CalendarEvents.ConferenceProperties_Summary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Summary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Summary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject)
	{
		if (summaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, summaryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.summaryMendixObject = summaryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static calendarevents.proxies.Summary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new calendarevents.proxies.Summary(context, mendixObject);
	}

	public static calendarevents.proxies.Summary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return calendarevents.proxies.Summary.initialize(context, mendixObject);
	}

	/**
	 * @return value of Kind
	 */
	public final java.lang.String getKind()
	{
		return getKind(getContext());
	}

	/**
	 * @param context
	 * @return value of Kind
	 */
	public final java.lang.String getKind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kind.toString());
	}

	/**
	 * Set value of Kind
	 * @param kind
	 */
	public final void setKind(java.lang.String kind)
	{
		setKind(getContext(), kind);
	}

	/**
	 * Set value of Kind
	 * @param context
	 * @param kind
	 */
	public final void setKind(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kind)
	{
		getMendixObject().setValue(context, MemberNames.Kind.toString(), kind);
	}

	/**
	 * @return value of Etag
	 */
	public final java.lang.String getEtag()
	{
		return getEtag(getContext());
	}

	/**
	 * @param context
	 * @return value of Etag
	 */
	public final java.lang.String getEtag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Etag.toString());
	}

	/**
	 * Set value of Etag
	 * @param etag
	 */
	public final void setEtag(java.lang.String etag)
	{
		setEtag(getContext(), etag);
	}

	/**
	 * Set value of Etag
	 * @param context
	 * @param etag
	 */
	public final void setEtag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String etag)
	{
		getMendixObject().setValue(context, MemberNames.Etag.toString(), etag);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Summary
	 */
	public final java.lang.String getSummary()
	{
		return getSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of Summary
	 */
	public final java.lang.String getSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Summary.toString());
	}

	/**
	 * Set value of Summary
	 * @param summary
	 */
	public final void setSummary(java.lang.String summary)
	{
		setSummary(getContext(), summary);
	}

	/**
	 * Set value of Summary
	 * @param context
	 * @param summary
	 */
	public final void setSummary(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String summary)
	{
		getMendixObject().setValue(context, MemberNames.Summary.toString(), summary);
	}

	/**
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone()
	{
		return getTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZone.toString());
	}

	/**
	 * Set value of TimeZone
	 * @param timezone
	 */
	public final void setTimeZone(java.lang.String timezone)
	{
		setTimeZone(getContext(), timezone);
	}

	/**
	 * Set value of TimeZone
	 * @param context
	 * @param timezone
	 */
	public final void setTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.TimeZone.toString(), timezone);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConferenceProperties_Summary
	 */
	public final calendarevents.proxies.ConferenceProperties getConferenceProperties_Summary() throws com.mendix.core.CoreException
	{
		return getConferenceProperties_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of ConferenceProperties_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final calendarevents.proxies.ConferenceProperties getConferenceProperties_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		calendarevents.proxies.ConferenceProperties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConferenceProperties_Summary.toString());
		if (identifier != null) {
			result = calendarevents.proxies.ConferenceProperties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConferenceProperties_Summary
	 * @param conferenceproperties_summary
	 */
	public final void setConferenceProperties_Summary(calendarevents.proxies.ConferenceProperties conferenceproperties_summary)
	{
		setConferenceProperties_Summary(getContext(), conferenceproperties_summary);
	}

	/**
	 * Set value of ConferenceProperties_Summary
	 * @param context
	 * @param conferenceproperties_summary
	 */
	public final void setConferenceProperties_Summary(com.mendix.systemwideinterfaces.core.IContext context, calendarevents.proxies.ConferenceProperties conferenceproperties_summary)
	{
		if (conferenceproperties_summary == null) {
			getMendixObject().setValue(context, MemberNames.ConferenceProperties_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConferenceProperties_Summary.toString(), conferenceproperties_summary.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return summaryMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final calendarevents.proxies.Summary that = (calendarevents.proxies.Summary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
