// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package carfinder.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CarFinder module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_Back_Step2Builder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Back_Step2");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_Ad_Back_Step2(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_Ad_Back_Step2Builder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_SaveBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Save");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_Ad_Save(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_Ad_SaveBuilder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_Step1Builder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Step1");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_Ad_Step1(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_Ad_Step1Builder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_Step2Builder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Step2");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_Ad_Step2(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_Ad_Step2Builder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_Step3Builder(
		carfinder.proxies.Ad _ad,
		carfinder.proxies.Car _car
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Step3");
		builder = builder.withParam("Ad", _ad);
		builder = builder.withParam("Car", _car);
		return builder;
	}

	public static void aCT_Ad_Step3(
		IContext context,
		carfinder.proxies.Ad _ad,
		carfinder.proxies.Car _car
	)
	{
		aCT_Ad_Step3Builder(
				_ad,
				_car
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Ad_Step4Builder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_Ad_Step4");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_Ad_Step4(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_Ad_Step4Builder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CarImage_AddBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_CarImage_Add");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_CarImage_Add(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_CarImage_AddBuilder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetFirstImageBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_GetFirstImage");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static java.util.List<carfinder.proxies.AdImage> aCT_GetFirstImage(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		Object result = aCT_GetFirstImageBuilder(
				_ad
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> carfinder.proxies.AdImage.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MotorcycleImage_AddBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_MotorcycleImage_Add");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_MotorcycleImage_Add(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_MotorcycleImage_AddBuilder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TruckImage_AddBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.ACT_TruckImage_Add");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void aCT_TruckImage_Add(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		aCT_TruckImage_AddBuilder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCO_Car_ValidationBuilder(
		carfinder.proxies.Car _car
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.BCO_Car_Validation");
		builder = builder.withParam("Car", _car);
		return builder;
	}

	public static boolean bCO_Car_Validation(
		IContext context,
		carfinder.proxies.Car _car
	)
	{
		Object result = bCO_Car_ValidationBuilder(
				_car
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Car_RetrieveBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.DS_Car_Retrieve");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static carfinder.proxies.Car dS_Car_Retrieve(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		Object result = dS_Car_RetrieveBuilder(
				_ad
			)
			.execute(context);
		return result == null ? null : carfinder.proxies.Car.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Car_CreareImageBuilder(
		carfinder.proxies.Ad _ad
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.SUB_Car_CreareImage");
		builder = builder.withParam("Ad", _ad);
		return builder;
	}

	public static void sUB_Car_CreareImage(
		IContext context,
		carfinder.proxies.Ad _ad
	)
	{
		sUB_Car_CreareImageBuilder(
				_ad
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_Car_DependenciesBuilder(
		carfinder.proxies.Car _car
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CarFinder.VAL_Car_Dependencies");
		builder = builder.withParam("Car", _car);
		return builder;
	}

	public static boolean vAL_Car_Dependencies(
		IContext context,
		carfinder.proxies.Car _car
	)
	{
		Object result = vAL_Car_DependenciesBuilder(
				_car
			)
			.execute(context);
		return (boolean) result;
	}
}
