// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the NativeMobile module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder callBuilder(
		mqttconnector.proxies.ConnectionDetail _connectionDetail
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeMobile.call");
		builder = builder.withParam("ConnectionDetail", _connectionDetail);
		return builder;
	}

	public static void call(
		IContext context,
		mqttconnector.proxies.ConnectionDetail _connectionDetail
	)
	{
		callBuilder(
				_connectionDetail
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder call_2Builder(
		mqttconnector.proxies.ConnectionDetail _connectionDetail
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeMobile.call_2");
		builder = builder.withParam("ConnectionDetail", _connectionDetail);
		return builder;
	}

	public static void call_2(
		IContext context,
		mqttconnector.proxies.ConnectionDetail _connectionDetail
	)
	{
		call_2Builder(
				_connectionDetail
			)
			.execute(context);
	}
}
