// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cashflow.proxies;

/**
 * This enumeration is used to indicate whether a transaction is considered income (positive value) or an expense (negative value)
 */
public enum ENUM_TransactionType
{
	Income(new java.lang.String[][] { new java.lang.String[] { "en_US", "Income" } }),
	Expense(new java.lang.String[][] { new java.lang.String[] { "en_US", "Expense" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_TransactionType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
