// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notification.proxies;

public enum ENUM_Notification_Status
{
	Information(new java.lang.String[][] { new java.lang.String[] { "en_US", "Information" } }),
	Severe(new java.lang.String[][] { new java.lang.String[] { "en_US", "Severe" } }),
	Warning(new java.lang.String[][] { new java.lang.String[] { "en_US", "Warning" } }),
	Error(new java.lang.String[][] { new java.lang.String[] { "en_US", "Error" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_Notification_Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
