// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cashflow.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the CashFlow module
	public static void aCT_Category_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CashFlow.ACT_Category_Create").withParams(params).execute(context);
	}
	public static void aCT_Category_Delete(IContext context, cashflow.proxies.Category _category)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Category", _category == null ? null : _category.getMendixObject());
		Core.microflowCall("CashFlow.ACT_Category_Delete").withParams(params).execute(context);
	}
	public static void aCT_Category_Save(IContext context, cashflow.proxies.Category _category)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Category", _category == null ? null : _category.getMendixObject());
		Core.microflowCall("CashFlow.ACT_Category_Save").withParams(params).execute(context);
	}
	public static void aCT_Transaction_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CashFlow.ACT_Transaction_Create").withParams(params).execute(context);
	}
	public static void aCT_Transaction_Delete(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("CashFlow.ACT_Transaction_Delete").withParams(params).execute(context);
	}
	public static void aCT_Transaction_Save(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("CashFlow.ACT_Transaction_Save").withParams(params).execute(context);
	}
	public static void oCH_Transaction_DeterminePositiveNegative_Alt(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("CashFlow.OCH_Transaction_DeterminePositiveNegative_Alt").withParams(params).execute(context);
	}
	public static void sUB_Category_Commit(IContext context, cashflow.proxies.Category _category)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Category", _category == null ? null : _category.getMendixObject());
		Core.microflowCall("CashFlow.SUB_Category_Commit").withParams(params).execute(context);
	}
	public static cashflow.proxies.Category sUB_Category_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("CashFlow.SUB_Category_Create").withParams(params).execute(context);
		return result == null ? null : cashflow.proxies.Category.initialize(context, result);
	}
	public static void sUB_Category_Delete(IContext context, cashflow.proxies.Category _category)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Category", _category == null ? null : _category.getMendixObject());
		Core.microflowCall("CashFlow.SUB_Category_Delete").withParams(params).execute(context);
	}
	public static boolean sUB_Category_Validate(IContext context, cashflow.proxies.Category _category)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Category", _category == null ? null : _category.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("CashFlow.SUB_Category_Validate").withParams(params).execute(context);
	}
	public static void sUB_Transaction_Commit(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("CashFlow.SUB_Transaction_Commit").withParams(params).execute(context);
	}
	public static cashflow.proxies.Transaction sUB_Transaction_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("CashFlow.SUB_Transaction_Create").withParams(params).execute(context);
		return result == null ? null : cashflow.proxies.Transaction.initialize(context, result);
	}
	public static void sUB_Transaction_Delete(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("CashFlow.SUB_Transaction_Delete").withParams(params).execute(context);
	}
	public static boolean sUB_Transaction_Validate(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("CashFlow.SUB_Transaction_Validate").withParams(params).execute(context);
	}
	public static boolean sUB_Transaction_Validate_Alt(IContext context, cashflow.proxies.Transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Transaction", _transaction == null ? null : _transaction.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("CashFlow.SUB_Transaction_Validate_Alt").withParams(params).execute(context);
	}
}
