// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rooms.proxies;

public class RoomPicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Rooms.RoomPicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		RoomPicture_Room("Rooms.RoomPicture_Room");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RoomPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RoomPicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject roomPictureMendixObject)
	{
		super(context, roomPictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, roomPictureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rooms.proxies.RoomPicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rooms.proxies.RoomPicture(context, mendixObject);
	}

	public static rooms.proxies.RoomPicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rooms.proxies.RoomPicture.initialize(context, mendixObject);
	}

	public static java.util.List<rooms.proxies.RoomPicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> rooms.proxies.RoomPicture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RoomPicture_Room
	 */
	public final rooms.proxies.Room getRoomPicture_Room() throws com.mendix.core.CoreException
	{
		return getRoomPicture_Room(getContext());
	}

	/**
	 * @param context
	 * @return value of RoomPicture_Room
	 * @throws com.mendix.core.CoreException
	 */
	public final rooms.proxies.Room getRoomPicture_Room(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rooms.proxies.Room result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RoomPicture_Room.toString());
		if (identifier != null) {
			result = rooms.proxies.Room.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RoomPicture_Room
	 * @param roompicture_room
	 */
	public final void setRoomPicture_Room(rooms.proxies.Room roompicture_room)
	{
		setRoomPicture_Room(getContext(), roompicture_room);
	}

	/**
	 * Set value of RoomPicture_Room
	 * @param context
	 * @param roompicture_room
	 */
	public final void setRoomPicture_Room(com.mendix.systemwideinterfaces.core.IContext context, rooms.proxies.Room roompicture_room)
	{
		if (roompicture_room == null) {
			getMendixObject().setValue(context, MemberNames.RoomPicture_Room.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RoomPicture_Room.toString(), roompicture_room.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rooms.proxies.RoomPicture that = (rooms.proxies.RoomPicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
