// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Ad implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject adMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Ad";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AdId("AdId"),
		Title("Title"),
		Description("Description"),
		PostingDate("PostingDate"),
		Ad_User("MyFirstModule.Ad_User"),
		Ad_Vehicle("MyFirstModule.Ad_Vehicle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ad(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ad(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adMendixObject)
	{
		if (adMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, adMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.adMendixObject = adMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Ad initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Ad(context, mendixObject);
	}

	public static myfirstmodule.proxies.Ad load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Ad.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Ad> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Ad.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AdId
	 */
	public final java.lang.Long getAdId()
	{
		return getAdId(getContext());
	}

	/**
	 * @param context
	 * @return value of AdId
	 */
	public final java.lang.Long getAdId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AdId.toString());
	}

	/**
	 * Set value of AdId
	 * @param adid
	 */
	public final void setAdId(java.lang.Long adid)
	{
		setAdId(getContext(), adid);
	}

	/**
	 * Set value of AdId
	 * @param context
	 * @param adid
	 */
	public final void setAdId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long adid)
	{
		getMendixObject().setValue(context, MemberNames.AdId.toString(), adid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of PostingDate
	 */
	public final java.util.Date getPostingDate()
	{
		return getPostingDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PostingDate
	 */
	public final java.util.Date getPostingDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostingDate.toString());
	}

	/**
	 * Set value of PostingDate
	 * @param postingdate
	 */
	public final void setPostingDate(java.util.Date postingdate)
	{
		setPostingDate(getContext(), postingdate);
	}

	/**
	 * Set value of PostingDate
	 * @param context
	 * @param postingdate
	 */
	public final void setPostingDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postingdate)
	{
		getMendixObject().setValue(context, MemberNames.PostingDate.toString(), postingdate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ad_User
	 */
	public final myfirstmodule.proxies.User getAd_User() throws com.mendix.core.CoreException
	{
		return getAd_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Ad_User
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.User getAd_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ad_User.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ad_User
	 * @param ad_user
	 */
	public final void setAd_User(myfirstmodule.proxies.User ad_user)
	{
		setAd_User(getContext(), ad_user);
	}

	/**
	 * Set value of Ad_User
	 * @param context
	 * @param ad_user
	 */
	public final void setAd_User(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.User ad_user)
	{
		if (ad_user == null) {
			getMendixObject().setValue(context, MemberNames.Ad_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ad_User.toString(), ad_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ad_Vehicle
	 */
	public final myfirstmodule.proxies.Vehicle getAd_Vehicle() throws com.mendix.core.CoreException
	{
		return getAd_Vehicle(getContext());
	}

	/**
	 * @param context
	 * @return value of Ad_Vehicle
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Vehicle getAd_Vehicle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Vehicle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ad_Vehicle.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Vehicle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ad_Vehicle
	 * @param ad_vehicle
	 */
	public final void setAd_Vehicle(myfirstmodule.proxies.Vehicle ad_vehicle)
	{
		setAd_Vehicle(getContext(), ad_vehicle);
	}

	/**
	 * Set value of Ad_Vehicle
	 * @param context
	 * @param ad_vehicle
	 */
	public final void setAd_Vehicle(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Vehicle ad_vehicle)
	{
		if (ad_vehicle == null) {
			getMendixObject().setValue(context, MemberNames.Ad_Vehicle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ad_Vehicle.toString(), ad_vehicle.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return adMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Ad that = (myfirstmodule.proxies.Ad) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
