// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GalleryTruck extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GalleryTruck";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		GalleryTruck_Truck("MyFirstModule.GalleryTruck_Truck");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GalleryTruck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GalleryTruck(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject galleryTruckMendixObject)
	{
		super(context, galleryTruckMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, galleryTruckMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.GalleryTruck initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GalleryTruck(context, mendixObject);
	}

	public static myfirstmodule.proxies.GalleryTruck load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GalleryTruck.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.GalleryTruck> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.GalleryTruck.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GalleryTruck_Truck
	 */
	public final myfirstmodule.proxies.Truck getGalleryTruck_Truck() throws com.mendix.core.CoreException
	{
		return getGalleryTruck_Truck(getContext());
	}

	/**
	 * @param context
	 * @return value of GalleryTruck_Truck
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Truck getGalleryTruck_Truck(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Truck result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GalleryTruck_Truck.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Truck.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GalleryTruck_Truck
	 * @param gallerytruck_truck
	 */
	public final void setGalleryTruck_Truck(myfirstmodule.proxies.Truck gallerytruck_truck)
	{
		setGalleryTruck_Truck(getContext(), gallerytruck_truck);
	}

	/**
	 * Set value of GalleryTruck_Truck
	 * @param context
	 * @param gallerytruck_truck
	 */
	public final void setGalleryTruck_Truck(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Truck gallerytruck_truck)
	{
		if (gallerytruck_truck == null) {
			getMendixObject().setValue(context, MemberNames.GalleryTruck_Truck.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GalleryTruck_Truck.toString(), gallerytruck_truck.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GalleryTruck that = (myfirstmodule.proxies.GalleryTruck) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
