define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../Mendix-Projects/Car-Finder/javascriptsource/deeplink/actions/Open_DeeplinkURL.js":
/*!****************************************************************************************************!*\
  !*** ../../../../Mendix-Projects/Car-Finder/javascriptsource/deeplink/actions/Open_DeeplinkURL.js ***!
  \****************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Open_DeeplinkURL: () => (/* binding */ Open_DeeplinkURL)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} deeplinkURL
 * @returns {Promise.<void>}
 */
async function Open_DeeplinkURL(deeplinkURL) {
  // BEGIN USER CODE
  window.open(deeplinkURL.get('URL'), '_blank');
  // END USER CODE
}

/***/ }),

/***/ "../../../../Mendix-Projects/Car-Finder/javascriptsource/email_connector/actions/JS_OpenSignInPage.js":
/*!************************************************************************************************************!*\
  !*** ../../../../Mendix-Projects/Car-Finder/javascriptsource/email_connector/actions/JS_OpenSignInPage.js ***!
  \************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_OpenSignInPage: () => (/* binding */ JS_OpenSignInPage)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} url
 * @returns {Promise.<void>}
 */
async function JS_OpenSignInPage(url) {
  // BEGIN USER CODE
  window.location.href = url;
  // END USER CODE
}

/***/ }),

/***/ "../../../../Mendix-Projects/Car-Finder/javascriptsource/forgotpassword/actions/RedirectPage.js":
/*!******************************************************************************************************!*\
  !*** ../../../../Mendix-Projects/Car-Finder/javascriptsource/forgotpassword/actions/RedirectPage.js ***!
  \******************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   RedirectPage: () => (/* binding */ RedirectPage)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uUID
 * @returns {Promise.<void>}
 */
async function RedirectPage(uUID) {
  // BEGIN USER CODE

  var form = document.createElement('form');
  document.body.appendChild(form);
  form.method = 'post';
  form.action = '/signin/';
  var input = document.createElement('input');
  input.type = 'hidden';
  input.name = 'uuid';
  input.value = uUID;
  form.appendChild(input);
  form.submit();
  return;
  // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!**************************************************************************!*\
  !*** ../../../../Mendix-Projects/Car-Finder/deployment/tmp/jsactions.js ***!
  \**************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   DeepLink$Open_DeeplinkURL: () => (/* binding */ DeepLink$Open_DeeplinkURL),
/* harmony export */   Email_Connector$JS_OpenSignInPage: () => (/* binding */ Email_Connector$JS_OpenSignInPage),
/* harmony export */   ForgotPassword$RedirectPage: () => (/* binding */ ForgotPassword$RedirectPage)
/* harmony export */ });
const Email_Connector$JS_OpenSignInPage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../Mendix-Projects/Car-Finder/javascriptsource/email_connector/actions/JS_OpenSignInPage */ "../../../../Mendix-Projects/Car-Finder/javascriptsource/email_connector/actions/JS_OpenSignInPage.js"))).JS_OpenSignInPage;
const DeepLink$Open_DeeplinkURL = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../Mendix-Projects/Car-Finder/javascriptsource/deeplink/actions/Open_DeeplinkURL */ "../../../../Mendix-Projects/Car-Finder/javascriptsource/deeplink/actions/Open_DeeplinkURL.js"))).Open_DeeplinkURL;
const ForgotPassword$RedirectPage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../Mendix-Projects/Car-Finder/javascriptsource/forgotpassword/actions/RedirectPage */ "../../../../Mendix-Projects/Car-Finder/javascriptsource/forgotpassword/actions/RedirectPage.js"))).RedirectPage;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUM2Qjs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNPLGVBQWVDLGdCQUFnQkEsQ0FBQ0MsV0FBVyxFQUFFO0VBQ25EO0VBQ0FDLE1BQU0sQ0FBQ0MsSUFBSSxDQUFDRixXQUFXLENBQUNHLEdBQUcsQ0FBQyxLQUFLLENBQUMsRUFBQyxRQUFRLENBQUM7RUFDNUM7QUFDRDs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ3BCQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNtQjtBQUNVOztBQUU3QjtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ08sZUFBZUMsaUJBQWlCQSxDQUFDQyxHQUFHLEVBQUU7RUFDNUM7RUFDQUosTUFBTSxDQUFDSyxRQUFRLENBQUNDLElBQUksR0FBR0YsR0FBRztFQUMxQjtBQUNEOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDckJBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ21CO0FBQ1U7O0FBRTdCO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlRyxZQUFZQSxDQUFDQyxJQUFJLEVBQUU7RUFDeEM7O0VBRUEsSUFBSUMsSUFBSSxHQUFHQyxRQUFRLENBQUNDLGFBQWEsQ0FBQyxNQUFNLENBQUM7RUFDdENELFFBQVEsQ0FBQ0UsSUFBSSxDQUFDQyxXQUFXLENBQUNKLElBQUksQ0FBQztFQUMvQkEsSUFBSSxDQUFDSyxNQUFNLEdBQUcsTUFBTTtFQUNwQkwsSUFBSSxDQUFDTSxNQUFNLEdBQUcsVUFBVTtFQUMzQixJQUFJQyxLQUFLLEdBQUdOLFFBQVEsQ0FBQ0MsYUFBYSxDQUFDLE9BQU8sQ0FBQztFQUMxQ0ssS0FBSyxDQUFDQyxJQUFJLEdBQUcsUUFBUTtFQUNyQkQsS0FBSyxDQUFDRSxJQUFJLEdBQUcsTUFBTTtFQUNiRixLQUFLLENBQUNHLEtBQUssR0FBR1gsSUFBSTtFQUNsQkMsSUFBSSxDQUFDSSxXQUFXLENBQUNHLEtBQUssQ0FBQztFQUUzQlAsSUFBSSxDQUFDVyxNQUFNLENBQUMsQ0FBQztFQUVoQjtFQUNBO0FBQ0Q7Ozs7Ozs7Ozs7O0FDbENBOzs7Ozs7Ozs7O0FDQUE7Ozs7OztVQ0FBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7O1VBRUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7Ozs7O1dDdEJBO1dBQ0E7V0FDQTtXQUNBO1dBQ0E7V0FDQSxpQ0FBaUMsV0FBVztXQUM1QztXQUNBOzs7OztXQ1BBO1dBQ0E7V0FDQTtXQUNBO1dBQ0EseUNBQXlDLHdDQUF3QztXQUNqRjtXQUNBO1dBQ0E7Ozs7O1dDUEE7Ozs7O1dDQUE7V0FDQTtXQUNBO1dBQ0EsdURBQXVELGlCQUFpQjtXQUN4RTtXQUNBLGdEQUFnRCxhQUFhO1dBQzdEOzs7Ozs7Ozs7Ozs7Ozs7OztBQ05PLE1BQU1DLGlDQUFpQyxHQUFHLE1BQUFBLENBQUEsS0FBWSxDQUFDLE1BQU0scVNBQW1ILEVBQUVsQixpQkFBaUI7QUFDbk0sTUFBTW1CLHlCQUF5QixHQUFHLE1BQUFBLENBQUEsS0FBWSxDQUFDLE1BQU0scVJBQTJHLEVBQUV4QixnQkFBZ0I7QUFDbEwsTUFBTXlCLDJCQUEyQixHQUFHLE1BQUFBLENBQUEsS0FBWSxDQUFDLE1BQU0seVJBQTZHLEVBQUVoQixZQUFZLEMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vTWVuZGl4LVByb2plY3RzL0Nhci1GaW5kZXIvamF2YXNjcmlwdHNvdXJjZS9kZWVwbGluay9hY3Rpb25zL09wZW5fRGVlcGxpbmtVUkwuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uL01lbmRpeC1Qcm9qZWN0cy9DYXItRmluZGVyL2phdmFzY3JpcHRzb3VyY2UvZW1haWxfY29ubmVjdG9yL2FjdGlvbnMvSlNfT3BlblNpZ25JblBhZ2UuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uL01lbmRpeC1Qcm9qZWN0cy9DYXItRmluZGVyL2phdmFzY3JpcHRzb3VyY2UvZm9yZ290cGFzc3dvcmQvYWN0aW9ucy9SZWRpcmVjdFBhZ2UuanMiLCJ3ZWJwYWNrOi8vL2V4dGVybmFsIGFtZCBcImJpZy5qc1wiIiwid2VicGFjazovLy9teC1nbG9iYWwiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svYm9vdHN0cmFwIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvY29tcGF0IGdldCBkZWZhdWx0IGV4cG9ydCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2RlZmluZSBwcm9wZXJ0eSBnZXR0ZXJzIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvaGFzT3duUHJvcGVydHkgc2hvcnRoYW5kIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvbWFrZSBuYW1lc3BhY2Ugb2JqZWN0Iiwid2VicGFjazovLy8uLi8uLi8uLi8uLi9NZW5kaXgtUHJvamVjdHMvQ2FyLUZpbmRlci9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7TXhPYmplY3R9IGRlZXBsaW5rVVJMXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBPcGVuX0RlZXBsaW5rVVJMKGRlZXBsaW5rVVJMKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0d2luZG93Lm9wZW4oZGVlcGxpbmtVUkwuZ2V0KCdVUkwnKSwnX2JsYW5rJyk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtzdHJpbmd9IHVybFxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfT3BlblNpZ25JblBhZ2UodXJsKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0d2luZG93LmxvY2F0aW9uLmhyZWYgPSB1cmw7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHBhcmFtIHtzdHJpbmd9IHVVSURcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFJlZGlyZWN0UGFnZSh1VUlEKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblxyXG5cdHZhciBmb3JtID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO1xyXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChmb3JtKTtcclxuICAgIGZvcm0ubWV0aG9kID0gJ3Bvc3QnO1xyXG4gICAgZm9ybS5hY3Rpb24gPSAnL3NpZ25pbi8nO1xyXG5cdHZhciBpbnB1dCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2lucHV0Jyk7XHJcblx0XHRpbnB1dC50eXBlID0gJ2hpZGRlbic7XHJcblx0XHRpbnB1dC5uYW1lID0gJ3V1aWQnO1xyXG4gICAgICAgIGlucHV0LnZhbHVlID0gdVVJRDtcclxuICAgICAgICBmb3JtLmFwcGVuZENoaWxkKGlucHV0KTtcclxuICAgIFxyXG4gICAgZm9ybS5zdWJtaXQoKTtcclxuXHJcblx0cmV0dXJuO1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCJtb2R1bGUuZXhwb3J0cyA9IF9fV0VCUEFDS19FWFRFUk5BTF9NT0RVTEVfYmlnX2pzX187IiwiLyogZW1wdHkgKi8iLCIvLyBUaGUgbW9kdWxlIGNhY2hlXG52YXIgX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fID0ge307XG5cbi8vIFRoZSByZXF1aXJlIGZ1bmN0aW9uXG5mdW5jdGlvbiBfX3dlYnBhY2tfcmVxdWlyZV9fKG1vZHVsZUlkKSB7XG5cdC8vIENoZWNrIGlmIG1vZHVsZSBpcyBpbiBjYWNoZVxuXHR2YXIgY2FjaGVkTW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXTtcblx0aWYgKGNhY2hlZE1vZHVsZSAhPT0gdW5kZWZpbmVkKSB7XG5cdFx0cmV0dXJuIGNhY2hlZE1vZHVsZS5leHBvcnRzO1xuXHR9XG5cdC8vIENyZWF0ZSBhIG5ldyBtb2R1bGUgKGFuZCBwdXQgaXQgaW50byB0aGUgY2FjaGUpXG5cdHZhciBtb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdID0ge1xuXHRcdC8vIG5vIG1vZHVsZS5pZCBuZWVkZWRcblx0XHQvLyBubyBtb2R1bGUubG9hZGVkIG5lZWRlZFxuXHRcdGV4cG9ydHM6IHt9XG5cdH07XG5cblx0Ly8gRXhlY3V0ZSB0aGUgbW9kdWxlIGZ1bmN0aW9uXG5cdF9fd2VicGFja19tb2R1bGVzX19bbW9kdWxlSWRdKG1vZHVsZSwgbW9kdWxlLmV4cG9ydHMsIF9fd2VicGFja19yZXF1aXJlX18pO1xuXG5cdC8vIFJldHVybiB0aGUgZXhwb3J0cyBvZiB0aGUgbW9kdWxlXG5cdHJldHVybiBtb2R1bGUuZXhwb3J0cztcbn1cblxuIiwiLy8gZ2V0RGVmYXVsdEV4cG9ydCBmdW5jdGlvbiBmb3IgY29tcGF0aWJpbGl0eSB3aXRoIG5vbi1oYXJtb255IG1vZHVsZXNcbl9fd2VicGFja19yZXF1aXJlX18ubiA9IChtb2R1bGUpID0+IHtcblx0dmFyIGdldHRlciA9IG1vZHVsZSAmJiBtb2R1bGUuX19lc01vZHVsZSA/XG5cdFx0KCkgPT4gKG1vZHVsZVsnZGVmYXVsdCddKSA6XG5cdFx0KCkgPT4gKG1vZHVsZSk7XG5cdF9fd2VicGFja19yZXF1aXJlX18uZChnZXR0ZXIsIHsgYTogZ2V0dGVyIH0pO1xuXHRyZXR1cm4gZ2V0dGVyO1xufTsiLCIvLyBkZWZpbmUgZ2V0dGVyIGZ1bmN0aW9ucyBmb3IgaGFybW9ueSBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLmQgPSAoZXhwb3J0cywgZGVmaW5pdGlvbikgPT4ge1xuXHRmb3IodmFyIGtleSBpbiBkZWZpbml0aW9uKSB7XG5cdFx0aWYoX193ZWJwYWNrX3JlcXVpcmVfXy5vKGRlZmluaXRpb24sIGtleSkgJiYgIV9fd2VicGFja19yZXF1aXJlX18ubyhleHBvcnRzLCBrZXkpKSB7XG5cdFx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywga2V5LCB7IGVudW1lcmFibGU6IHRydWUsIGdldDogZGVmaW5pdGlvbltrZXldIH0pO1xuXHRcdH1cblx0fVxufTsiLCJfX3dlYnBhY2tfcmVxdWlyZV9fLm8gPSAob2JqLCBwcm9wKSA9PiAoT2JqZWN0LnByb3RvdHlwZS5oYXNPd25Qcm9wZXJ0eS5jYWxsKG9iaiwgcHJvcCkpIiwiLy8gZGVmaW5lIF9fZXNNb2R1bGUgb24gZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5yID0gKGV4cG9ydHMpID0+IHtcblx0aWYodHlwZW9mIFN5bWJvbCAhPT0gJ3VuZGVmaW5lZCcgJiYgU3ltYm9sLnRvU3RyaW5nVGFnKSB7XG5cdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIFN5bWJvbC50b1N0cmluZ1RhZywgeyB2YWx1ZTogJ01vZHVsZScgfSk7XG5cdH1cblx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICdfX2VzTW9kdWxlJywgeyB2YWx1ZTogdHJ1ZSB9KTtcbn07IiwiZXhwb3J0IGNvbnN0IEVtYWlsX0Nvbm5lY3RvciRKU19PcGVuU2lnbkluUGFnZSA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJEOi9VS1RDIFBST0dSQU1NSU5HL01lbmRpeC1Qcm9qZWN0cy9DYXItRmluZGVyL2phdmFzY3JpcHRzb3VyY2UvZW1haWxfY29ubmVjdG9yL2FjdGlvbnMvSlNfT3BlblNpZ25JblBhZ2VcIikpLkpTX09wZW5TaWduSW5QYWdlO1xuZXhwb3J0IGNvbnN0IERlZXBMaW5rJE9wZW5fRGVlcGxpbmtVUkwgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRDovVUtUQyBQUk9HUkFNTUlORy9NZW5kaXgtUHJvamVjdHMvQ2FyLUZpbmRlci9qYXZhc2NyaXB0c291cmNlL2RlZXBsaW5rL2FjdGlvbnMvT3Blbl9EZWVwbGlua1VSTFwiKSkuT3Blbl9EZWVwbGlua1VSTDtcbmV4cG9ydCBjb25zdCBGb3Jnb3RQYXNzd29yZCRSZWRpcmVjdFBhZ2UgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiRDovVUtUQyBQUk9HUkFNTUlORy9NZW5kaXgtUHJvamVjdHMvQ2FyLUZpbmRlci9qYXZhc2NyaXB0c291cmNlL2ZvcmdvdHBhc3N3b3JkL2FjdGlvbnMvUmVkaXJlY3RQYWdlXCIpKS5SZWRpcmVjdFBhZ2U7XG4iXSwibmFtZXMiOlsiQmlnIiwiT3Blbl9EZWVwbGlua1VSTCIsImRlZXBsaW5rVVJMIiwid2luZG93Iiwib3BlbiIsImdldCIsIkpTX09wZW5TaWduSW5QYWdlIiwidXJsIiwibG9jYXRpb24iLCJocmVmIiwiUmVkaXJlY3RQYWdlIiwidVVJRCIsImZvcm0iLCJkb2N1bWVudCIsImNyZWF0ZUVsZW1lbnQiLCJib2R5IiwiYXBwZW5kQ2hpbGQiLCJtZXRob2QiLCJhY3Rpb24iLCJpbnB1dCIsInR5cGUiLCJuYW1lIiwidmFsdWUiLCJzdWJtaXQiLCJFbWFpbF9Db25uZWN0b3IkSlNfT3BlblNpZ25JblBhZ2UiLCJEZWVwTGluayRPcGVuX0RlZXBsaW5rVVJMIiwiRm9yZ290UGFzc3dvcmQkUmVkaXJlY3RQYWdlIl0sInNvdXJjZVJvb3QiOiIifQ==