// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Main module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Main.ACT_GetUser");
		return builder;
	}

	public static usermanagement.proxies.User aCT_GetUser(IContext context)
	{
		Object result = aCT_GetUserBuilder().execute(context);
		return result == null ? null : usermanagement.proxies.User.initialize(context, (IMendixObject) result);
	}
}
